// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/market/v1/event.proto

package v1

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	v1 "pkg.akt.dev/go/node/deployment/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventOrderCreated is triggered when an order is created.
// It contains all the information required to identify an order.
type EventOrderCreated struct {
	// Id is the unique identifier of the Order.
	ID OrderID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
}

func (m *EventOrderCreated) Reset()         { *m = EventOrderCreated{} }
func (m *EventOrderCreated) String() string { return proto.CompactTextString(m) }
func (*EventOrderCreated) ProtoMessage()    {}
func (*EventOrderCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_95cc31d2d9808e8a, []int{0}
}
func (m *EventOrderCreated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventOrderCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventOrderCreated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventOrderCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventOrderCreated.Merge(m, src)
}
func (m *EventOrderCreated) XXX_Size() int {
	return m.Size()
}
func (m *EventOrderCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventOrderCreated.DiscardUnknown(m)
}

var xxx_messageInfo_EventOrderCreated proto.InternalMessageInfo

func (m *EventOrderCreated) GetID() OrderID {
	if m != nil {
		return m.ID
	}
	return OrderID{}
}

// EventOrderClosed is triggered when an order is closed.
// It contains all the information required to identify an order.
type EventOrderClosed struct {
	// Id is the unique identifier of the Order.
	ID OrderID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
}

func (m *EventOrderClosed) Reset()         { *m = EventOrderClosed{} }
func (m *EventOrderClosed) String() string { return proto.CompactTextString(m) }
func (*EventOrderClosed) ProtoMessage()    {}
func (*EventOrderClosed) Descriptor() ([]byte, []int) {
	return fileDescriptor_95cc31d2d9808e8a, []int{1}
}
func (m *EventOrderClosed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventOrderClosed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventOrderClosed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventOrderClosed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventOrderClosed.Merge(m, src)
}
func (m *EventOrderClosed) XXX_Size() int {
	return m.Size()
}
func (m *EventOrderClosed) XXX_DiscardUnknown() {
	xxx_messageInfo_EventOrderClosed.DiscardUnknown(m)
}

var xxx_messageInfo_EventOrderClosed proto.InternalMessageInfo

func (m *EventOrderClosed) GetID() OrderID {
	if m != nil {
		return m.ID
	}
	return OrderID{}
}

// EventBidCreated is triggered when a bid is created.
// It contains all the information required to identify a bid.
type EventBidCreated struct {
	// Id is the unique identifier of the Bid.
	ID BidID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	// Price stated on the Bid.
	Price types.DecCoin `protobuf:"bytes,3,opt,name=price,proto3" json:"price" yaml:"price"`
}

func (m *EventBidCreated) Reset()         { *m = EventBidCreated{} }
func (m *EventBidCreated) String() string { return proto.CompactTextString(m) }
func (*EventBidCreated) ProtoMessage()    {}
func (*EventBidCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_95cc31d2d9808e8a, []int{2}
}
func (m *EventBidCreated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBidCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBidCreated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBidCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBidCreated.Merge(m, src)
}
func (m *EventBidCreated) XXX_Size() int {
	return m.Size()
}
func (m *EventBidCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBidCreated.DiscardUnknown(m)
}

var xxx_messageInfo_EventBidCreated proto.InternalMessageInfo

func (m *EventBidCreated) GetID() BidID {
	if m != nil {
		return m.ID
	}
	return BidID{}
}

func (m *EventBidCreated) GetPrice() types.DecCoin {
	if m != nil {
		return m.Price
	}
	return types.DecCoin{}
}

// EventBidClosed is triggered when a bid is closed.
// It contains all the information required to identify a bid.
type EventBidClosed struct {
	// Id is the unique identifier of the Bid.
	ID BidID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
}

func (m *EventBidClosed) Reset()         { *m = EventBidClosed{} }
func (m *EventBidClosed) String() string { return proto.CompactTextString(m) }
func (*EventBidClosed) ProtoMessage()    {}
func (*EventBidClosed) Descriptor() ([]byte, []int) {
	return fileDescriptor_95cc31d2d9808e8a, []int{3}
}
func (m *EventBidClosed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBidClosed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBidClosed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBidClosed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBidClosed.Merge(m, src)
}
func (m *EventBidClosed) XXX_Size() int {
	return m.Size()
}
func (m *EventBidClosed) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBidClosed.DiscardUnknown(m)
}

var xxx_messageInfo_EventBidClosed proto.InternalMessageInfo

func (m *EventBidClosed) GetID() BidID {
	if m != nil {
		return m.ID
	}
	return BidID{}
}

// EventLeaseCreated is triggered when a lease is created.
// It contains all the information required to identify a lease.
type EventLeaseCreated struct {
	// Id is the unique identifier of the Lease.
	ID LeaseID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	// Price settled for the lease.
	Price types.DecCoin `protobuf:"bytes,3,opt,name=price,proto3" json:"price" yaml:"price"`
}

func (m *EventLeaseCreated) Reset()         { *m = EventLeaseCreated{} }
func (m *EventLeaseCreated) String() string { return proto.CompactTextString(m) }
func (*EventLeaseCreated) ProtoMessage()    {}
func (*EventLeaseCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_95cc31d2d9808e8a, []int{4}
}
func (m *EventLeaseCreated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventLeaseCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventLeaseCreated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventLeaseCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLeaseCreated.Merge(m, src)
}
func (m *EventLeaseCreated) XXX_Size() int {
	return m.Size()
}
func (m *EventLeaseCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLeaseCreated.DiscardUnknown(m)
}

var xxx_messageInfo_EventLeaseCreated proto.InternalMessageInfo

func (m *EventLeaseCreated) GetID() LeaseID {
	if m != nil {
		return m.ID
	}
	return LeaseID{}
}

func (m *EventLeaseCreated) GetPrice() types.DecCoin {
	if m != nil {
		return m.Price
	}
	return types.DecCoin{}
}

// EventLeaseClosed is triggered when a lease is closed.
// It contains all the information required to identify a lease.
type EventLeaseClosed struct {
	// Id is the unique identifier of the Lease.
	ID     LeaseID           `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	Reason LeaseClosedReason `protobuf:"varint,2,opt,name=reason,proto3,enum=akash.market.v1.LeaseClosedReason" json:"reason" yaml:"reason"`
}

func (m *EventLeaseClosed) Reset()         { *m = EventLeaseClosed{} }
func (m *EventLeaseClosed) String() string { return proto.CompactTextString(m) }
func (*EventLeaseClosed) ProtoMessage()    {}
func (*EventLeaseClosed) Descriptor() ([]byte, []int) {
	return fileDescriptor_95cc31d2d9808e8a, []int{5}
}
func (m *EventLeaseClosed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventLeaseClosed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventLeaseClosed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventLeaseClosed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLeaseClosed.Merge(m, src)
}
func (m *EventLeaseClosed) XXX_Size() int {
	return m.Size()
}
func (m *EventLeaseClosed) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLeaseClosed.DiscardUnknown(m)
}

var xxx_messageInfo_EventLeaseClosed proto.InternalMessageInfo

func (m *EventLeaseClosed) GetID() LeaseID {
	if m != nil {
		return m.ID
	}
	return LeaseID{}
}

func (m *EventLeaseClosed) GetReason() LeaseClosedReason {
	if m != nil {
		return m.Reason
	}
	return LeaseClosedReasonInvalid
}

// EventLeaseReclaimStarted is triggered when a provider initiates reclamation on a lease.
type EventLeaseReclaimStarted struct {
	// Id is the unique identifier of the Lease.
	ID LeaseID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	// reason is the provider's stated reason for reclamation.
	Reason LeaseClosedReason `protobuf:"varint,2,opt,name=reason,proto3,enum=akash.market.v1.LeaseClosedReason" json:"reason" yaml:"reason"`
	// deadline is the unix timestamp when the reclamation window expires.
	Deadline int64 `protobuf:"varint,3,opt,name=deadline,proto3" json:"deadline" yaml:"deadline"`
}

func (m *EventLeaseReclaimStarted) Reset()         { *m = EventLeaseReclaimStarted{} }
func (m *EventLeaseReclaimStarted) String() string { return proto.CompactTextString(m) }
func (*EventLeaseReclaimStarted) ProtoMessage()    {}
func (*EventLeaseReclaimStarted) Descriptor() ([]byte, []int) {
	return fileDescriptor_95cc31d2d9808e8a, []int{6}
}
func (m *EventLeaseReclaimStarted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventLeaseReclaimStarted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventLeaseReclaimStarted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventLeaseReclaimStarted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLeaseReclaimStarted.Merge(m, src)
}
func (m *EventLeaseReclaimStarted) XXX_Size() int {
	return m.Size()
}
func (m *EventLeaseReclaimStarted) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLeaseReclaimStarted.DiscardUnknown(m)
}

var xxx_messageInfo_EventLeaseReclaimStarted proto.InternalMessageInfo

func (m *EventLeaseReclaimStarted) GetID() LeaseID {
	if m != nil {
		return m.ID
	}
	return LeaseID{}
}

func (m *EventLeaseReclaimStarted) GetReason() LeaseClosedReason {
	if m != nil {
		return m.Reason
	}
	return LeaseClosedReasonInvalid
}

func (m *EventLeaseReclaimStarted) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

// EventVolumeAttached is triggered when a compute lease attaches an
// externally-leased volume.
type EventVolumeAttached struct {
	// LeaseId is the unique identifier of the compute lease.
	LeaseID LeaseID `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id" yaml:"lease_id"`
	// Volume references the attached volume.
	Volume v1.VolumeRef `protobuf:"bytes,2,opt,name=volume,proto3" json:"volume" yaml:"volume"`
}

func (m *EventVolumeAttached) Reset()         { *m = EventVolumeAttached{} }
func (m *EventVolumeAttached) String() string { return proto.CompactTextString(m) }
func (*EventVolumeAttached) ProtoMessage()    {}
func (*EventVolumeAttached) Descriptor() ([]byte, []int) {
	return fileDescriptor_95cc31d2d9808e8a, []int{7}
}
func (m *EventVolumeAttached) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventVolumeAttached) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventVolumeAttached.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventVolumeAttached) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventVolumeAttached.Merge(m, src)
}
func (m *EventVolumeAttached) XXX_Size() int {
	return m.Size()
}
func (m *EventVolumeAttached) XXX_DiscardUnknown() {
	xxx_messageInfo_EventVolumeAttached.DiscardUnknown(m)
}

var xxx_messageInfo_EventVolumeAttached proto.InternalMessageInfo

func (m *EventVolumeAttached) GetLeaseID() LeaseID {
	if m != nil {
		return m.LeaseID
	}
	return LeaseID{}
}

func (m *EventVolumeAttached) GetVolume() v1.VolumeRef {
	if m != nil {
		return m.Volume
	}
	return v1.VolumeRef{}
}

// EventVolumeDetached is triggered when a compute lease detaches from an
// externally-leased volume, on any close path.
type EventVolumeDetached struct {
	// LeaseId is the unique identifier of the compute lease.
	LeaseID LeaseID `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id" yaml:"lease_id"`
	// Volume references the detached volume.
	Volume v1.VolumeRef `protobuf:"bytes,2,opt,name=volume,proto3" json:"volume" yaml:"volume"`
	// Reason is why the detach happened.
	Reason LeaseClosedReason `protobuf:"varint,3,opt,name=reason,proto3,enum=akash.market.v1.LeaseClosedReason" json:"reason" yaml:"reason"`
}

func (m *EventVolumeDetached) Reset()         { *m = EventVolumeDetached{} }
func (m *EventVolumeDetached) String() string { return proto.CompactTextString(m) }
func (*EventVolumeDetached) ProtoMessage()    {}
func (*EventVolumeDetached) Descriptor() ([]byte, []int) {
	return fileDescriptor_95cc31d2d9808e8a, []int{8}
}
func (m *EventVolumeDetached) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventVolumeDetached) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventVolumeDetached.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventVolumeDetached) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventVolumeDetached.Merge(m, src)
}
func (m *EventVolumeDetached) XXX_Size() int {
	return m.Size()
}
func (m *EventVolumeDetached) XXX_DiscardUnknown() {
	xxx_messageInfo_EventVolumeDetached.DiscardUnknown(m)
}

var xxx_messageInfo_EventVolumeDetached proto.InternalMessageInfo

func (m *EventVolumeDetached) GetLeaseID() LeaseID {
	if m != nil {
		return m.LeaseID
	}
	return LeaseID{}
}

func (m *EventVolumeDetached) GetVolume() v1.VolumeRef {
	if m != nil {
		return m.Volume
	}
	return v1.VolumeRef{}
}

func (m *EventVolumeDetached) GetReason() LeaseClosedReason {
	if m != nil {
		return m.Reason
	}
	return LeaseClosedReasonInvalid
}

func init() {
	proto.RegisterType((*EventOrderCreated)(nil), "akash.market.v1.EventOrderCreated")
	proto.RegisterType((*EventOrderClosed)(nil), "akash.market.v1.EventOrderClosed")
	proto.RegisterType((*EventBidCreated)(nil), "akash.market.v1.EventBidCreated")
	proto.RegisterType((*EventBidClosed)(nil), "akash.market.v1.EventBidClosed")
	proto.RegisterType((*EventLeaseCreated)(nil), "akash.market.v1.EventLeaseCreated")
	proto.RegisterType((*EventLeaseClosed)(nil), "akash.market.v1.EventLeaseClosed")
	proto.RegisterType((*EventLeaseReclaimStarted)(nil), "akash.market.v1.EventLeaseReclaimStarted")
	proto.RegisterType((*EventVolumeAttached)(nil), "akash.market.v1.EventVolumeAttached")
	proto.RegisterType((*EventVolumeDetached)(nil), "akash.market.v1.EventVolumeDetached")
}

func init() { proto.RegisterFile("akash/market/v1/event.proto", fileDescriptor_95cc31d2d9808e8a) }

var fileDescriptor_95cc31d2d9808e8a = []byte{
	// 605 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x55, 0x4f, 0x6b, 0x13, 0x4f,
	0x18, 0xce, 0x6c, 0x7f, 0xbf, 0xb6, 0x4e, 0xb5, 0xd5, 0x28, 0x12, 0x5b, 0xbb, 0x13, 0xf6, 0xd4,
	0xd3, 0x2c, 0x89, 0x07, 0xa1, 0x9e, 0xdc, 0xa6, 0x48, 0x40, 0x10, 0x57, 0x50, 0x10, 0x44, 0x26,
	0x3b, 0xaf, 0xe9, 0x90, 0xdd, 0x9d, 0xb0, 0xbb, 0x2e, 0xe4, 0x5b, 0xf8, 0x11, 0xfc, 0x0a, 0x0a,
	0x5e, 0xfc, 0x04, 0x3d, 0xf6, 0xa8, 0x97, 0x45, 0x92, 0x8b, 0xe4, 0x98, 0x2f, 0xa0, 0xec, 0xcc,
	0xe4, 0x8f, 0xad, 0x85, 0x08, 0x15, 0xd1, 0xdb, 0xce, 0xfb, 0xbc, 0xef, 0xfb, 0x3c, 0xef, 0x9f,
	0x9d, 0xc1, 0x3b, 0xac, 0xc7, 0xd2, 0x23, 0x37, 0x62, 0x49, 0x0f, 0x32, 0x37, 0x6f, 0xb8, 0x90,
	0x43, 0x9c, 0xd1, 0x7e, 0x22, 0x33, 0x59, 0xdd, 0x52, 0x20, 0xd5, 0x20, 0xcd, 0x1b, 0xdb, 0x37,
	0xba, 0xb2, 0x2b, 0x15, 0xe6, 0x96, 0x5f, 0xda, 0x6d, 0xdb, 0x0e, 0x64, 0x1a, 0xc9, 0xd4, 0xed,
	0xb0, 0x14, 0xdc, 0xbc, 0xd1, 0x81, 0x8c, 0x35, 0xdc, 0x40, 0x8a, 0xd8, 0xe0, 0x75, 0xcd, 0xc1,
	0xa1, 0x1f, 0xca, 0x41, 0x04, 0xb1, 0xe2, 0xc9, 0x65, 0xf8, 0x3a, 0x02, 0xe3, 0x71, 0xeb, 0xb4,
	0x8a, 0x8e, 0xe0, 0x06, 0x3a, 0x23, 0x50, 0x26, 0x1c, 0x92, 0xf3, 0xc0, 0x10, 0x58, 0x0a, 0xe7,
	0x81, 0xd9, 0xa0, 0x0f, 0xa9, 0x06, 0x9d, 0x0e, 0xbe, 0x76, 0x58, 0x56, 0xfa, 0xa8, 0xcc, 0x76,
	0x90, 0x00, 0xcb, 0x80, 0x57, 0x1f, 0x60, 0x4b, 0xf0, 0x1a, 0xaa, 0xa3, 0xbd, 0x8d, 0x66, 0x8d,
	0x9e, 0x2a, 0x9e, 0x2a, 0xd7, 0x76, 0xcb, 0xdb, 0x3d, 0x2e, 0x48, 0x65, 0x58, 0x10, 0xab, 0xdd,
	0x1a, 0x17, 0xc4, 0x12, 0x7c, 0x52, 0x90, 0x4b, 0x03, 0x16, 0x85, 0xfb, 0x8e, 0xe0, 0x8e, 0x6f,
	0x09, 0xbe, 0xff, 0xdf, 0xd7, 0xb7, 0x04, 0x39, 0x0c, 0x5f, 0x5d, 0xe0, 0x08, 0x65, 0x7a, 0xf1,
	0x14, 0xef, 0x10, 0xde, 0x52, 0x1c, 0x9e, 0xe0, 0xd3, 0x2a, 0x0e, 0x17, 0x28, 0x6e, 0x9e, 0xa1,
	0xf0, 0x04, 0x5f, 0x8a, 0xa0, 0xfa, 0x18, 0xff, 0xdf, 0x4f, 0x44, 0x00, 0xb5, 0x15, 0x95, 0xe9,
	0x36, 0xd5, 0x53, 0xa6, 0xe5, 0x94, 0xa9, 0x99, 0x32, 0x6d, 0x41, 0x70, 0x20, 0x45, 0xac, 0xf3,
	0x8d, 0x0b, 0xa2, 0x43, 0x26, 0x05, 0xb9, 0xac, 0x93, 0xa9, 0xa3, 0xe3, 0x6b, 0xb3, 0xd1, 0xfc,
	0x02, 0x6f, 0xce, 0x24, 0xeb, 0xa6, 0x5c, 0x8c, 0x62, 0x93, 0xfe, 0x03, 0x32, 0xa3, 0x7d, 0x58,
	0xee, 0xc2, 0x72, 0xa3, 0x55, 0xae, 0x7f, 0xb8, 0x2d, 0x1f, 0x91, 0x59, 0x17, 0xad, 0x7b, 0x99,
	0x75, 0xf9, 0x05, 0xd9, 0xcf, 0xf0, 0x6a, 0x02, 0x2c, 0x95, 0x71, 0xcd, 0xaa, 0xa3, 0xbd, 0xcd,
	0xa6, 0xf3, 0xf3, 0x64, 0x9a, 0xd6, 0x57, 0x9e, 0xde, 0xce, 0xb8, 0x20, 0x26, 0x6a, 0x52, 0x90,
	0x2b, 0x3a, 0xa1, 0x3e, 0x3b, 0xbe, 0x01, 0x8c, 0xf8, 0x6f, 0x08, 0xd7, 0xe6, 0xe2, 0x7d, 0x08,
	0x42, 0x26, 0xa2, 0x27, 0x19, 0x4b, 0xb2, 0xbf, 0xa1, 0x88, 0xea, 0x3d, 0xbc, 0xce, 0x81, 0xf1,
	0x50, 0xc4, 0x7a, 0xae, 0x2b, 0x1e, 0x19, 0x17, 0x64, 0x66, 0x9b, 0x14, 0x64, 0x4b, 0x07, 0x4e,
	0x2d, 0x8e, 0x3f, 0x03, 0x4d, 0x07, 0x3e, 0x23, 0x7c, 0x5d, 0x75, 0xe0, 0xa9, 0xba, 0xd8, 0xee,
	0x67, 0x19, 0x0b, 0x8e, 0x80, 0x57, 0x03, 0xbc, 0xae, 0x2e, 0xa5, 0x97, 0x4b, 0xb4, 0x80, 0x9a,
	0x16, 0xac, 0x19, 0x43, 0xa9, 0x61, 0x1a, 0x3c, 0xd7, 0x30, 0xb5, 0x38, 0xfe, 0x9a, 0xfa, 0x6c,
	0xab, 0xc6, 0xe8, 0xfb, 0x54, 0x35, 0x66, 0xa3, 0x69, 0x1b, 0x8a, 0xf9, 0x95, 0x5b, 0xd2, 0x68,
	0x65, 0x3e, 0xbc, 0xf2, 0x88, 0xd9, 0x4b, 0x13, 0x35, 0x6f, 0x8c, 0x3e, 0x3b, 0xbe, 0x01, 0x4c,
	0x6d, 0xef, 0xad, 0x1f, 0x6a, 0x6b, 0xc1, 0xbf, 0x50, 0xdb, 0xc2, 0x36, 0xad, 0xfc, 0x86, 0x5f,
	0xc2, 0xbb, 0x7b, 0x3c, 0xb4, 0xd1, 0xc9, 0xd0, 0x46, 0x5f, 0x86, 0x36, 0x7a, 0x33, 0xb2, 0x2b,
	0x27, 0x23, 0xbb, 0xf2, 0x69, 0x64, 0x57, 0x9e, 0xef, 0xf6, 0x7b, 0x5d, 0xca, 0x7a, 0x19, 0xe5,
	0x90, 0xbb, 0x5d, 0xe9, 0xc6, 0x92, 0xc3, 0xfc, 0x99, 0xea, 0xac, 0xaa, 0x17, 0xea, 0xce, 0xf7,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x65, 0xc2, 0xad, 0x9b, 0x07, 0x00, 0x00,
}

func (this *EventOrderCreated) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventOrderCreated)
	if !ok {
		that2, ok := that.(EventOrderCreated)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(&that1.ID) {
		return false
	}
	return true
}
func (this *EventOrderClosed) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventOrderClosed)
	if !ok {
		that2, ok := that.(EventOrderClosed)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(&that1.ID) {
		return false
	}
	return true
}
func (this *EventBidCreated) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventBidCreated)
	if !ok {
		that2, ok := that.(EventBidCreated)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(&that1.ID) {
		return false
	}
	if !this.Price.Equal(&that1.Price) {
		return false
	}
	return true
}
func (this *EventBidClosed) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventBidClosed)
	if !ok {
		that2, ok := that.(EventBidClosed)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(&that1.ID) {
		return false
	}
	return true
}
func (this *EventLeaseCreated) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventLeaseCreated)
	if !ok {
		that2, ok := that.(EventLeaseCreated)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(&that1.ID) {
		return false
	}
	if !this.Price.Equal(&that1.Price) {
		return false
	}
	return true
}
func (this *EventLeaseClosed) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventLeaseClosed)
	if !ok {
		that2, ok := that.(EventLeaseClosed)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(&that1.ID) {
		return false
	}
	if this.Reason != that1.Reason {
		return false
	}
	return true
}
func (this *EventLeaseReclaimStarted) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventLeaseReclaimStarted)
	if !ok {
		that2, ok := that.(EventLeaseReclaimStarted)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(&that1.ID) {
		return false
	}
	if this.Reason != that1.Reason {
		return false
	}
	if this.Deadline != that1.Deadline {
		return false
	}
	return true
}
func (this *EventVolumeAttached) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventVolumeAttached)
	if !ok {
		that2, ok := that.(EventVolumeAttached)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.LeaseID.Equal(&that1.LeaseID) {
		return false
	}
	if !this.Volume.Equal(&that1.Volume) {
		return false
	}
	return true
}
func (this *EventVolumeDetached) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventVolumeDetached)
	if !ok {
		that2, ok := that.(EventVolumeDetached)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.LeaseID.Equal(&that1.LeaseID) {
		return false
	}
	if !this.Volume.Equal(&that1.Volume) {
		return false
	}
	if this.Reason != that1.Reason {
		return false
	}
	return true
}
func (m *EventOrderCreated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventOrderCreated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventOrderCreated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventOrderClosed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventOrderClosed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventOrderClosed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventBidCreated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBidCreated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBidCreated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Price.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventBidClosed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBidClosed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBidClosed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventLeaseCreated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventLeaseCreated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventLeaseCreated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Price.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventLeaseClosed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventLeaseClosed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventLeaseClosed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reason != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Reason))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventLeaseReclaimStarted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventLeaseReclaimStarted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventLeaseReclaimStarted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Deadline != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Deadline))
		i--
		dAtA[i] = 0x18
	}
	if m.Reason != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Reason))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventVolumeAttached) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventVolumeAttached) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventVolumeAttached) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Volume.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.LeaseID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventVolumeDetached) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventVolumeDetached) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventVolumeDetached) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reason != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Reason))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.Volume.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.LeaseID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventOrderCreated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventOrderClosed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventBidCreated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = m.Price.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventBidClosed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventLeaseCreated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = m.Price.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventLeaseClosed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvent(uint64(l))
	if m.Reason != 0 {
		n += 1 + sovEvent(uint64(m.Reason))
	}
	return n
}

func (m *EventLeaseReclaimStarted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvent(uint64(l))
	if m.Reason != 0 {
		n += 1 + sovEvent(uint64(m.Reason))
	}
	if m.Deadline != 0 {
		n += 1 + sovEvent(uint64(m.Deadline))
	}
	return n
}

func (m *EventVolumeAttached) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.LeaseID.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = m.Volume.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventVolumeDetached) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.LeaseID.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = m.Volume.Size()
	n += 1 + l + sovEvent(uint64(l))
	if m.Reason != 0 {
		n += 1 + sovEvent(uint64(m.Reason))
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventOrderCreated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventOrderCreated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventOrderCreated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventOrderClosed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventOrderClosed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventOrderClosed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBidCreated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBidCreated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBidCreated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBidClosed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBidClosed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBidClosed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventLeaseCreated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventLeaseCreated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventLeaseCreated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventLeaseClosed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventLeaseClosed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventLeaseClosed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			m.Reason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reason |= LeaseClosedReason(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventLeaseReclaimStarted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventLeaseReclaimStarted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventLeaseReclaimStarted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			m.Reason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reason |= LeaseClosedReason(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deadline", wireType)
			}
			m.Deadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Deadline |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventVolumeAttached) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventVolumeAttached: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventVolumeAttached: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaseID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LeaseID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Volume", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Volume.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventVolumeDetached) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventVolumeDetached: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventVolumeDetached: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaseID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LeaseID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Volume", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Volume.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			m.Reason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reason |= LeaseClosedReason(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
