// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/market/v2beta1/bid.proto

package v2beta1

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	v1 "pkg.akt.dev/go/node/market/v1"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BidState is an enum which refers to state of bid.
type Bid_State int32

const (
	// Prefix should start with 0 in enum. So declaring dummy state.
	BidStateInvalid Bid_State = 0
	// BidOpen denotes state for bid open.
	BidOpen Bid_State = 1
	// BidMatched denotes state for bid open.
	BidActive Bid_State = 2
	// BidLost denotes state for bid lost.
	BidLost Bid_State = 3
	// BidClosed denotes state for bid closed.
	BidClosed Bid_State = 4
)

var Bid_State_name = map[int32]string{
	0: "invalid",
	1: "open",
	2: "active",
	3: "lost",
	4: "closed",
}

var Bid_State_value = map[string]int32{
	"invalid": 0,
	"open":    1,
	"active":  2,
	"lost":    3,
	"closed":  4,
}

func (x Bid_State) String() string {
	return proto.EnumName(Bid_State_name, int32(x))
}

func (Bid_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e525959eb5a7d93, []int{0, 0}
}

// Bid stores BidID, state of bid and price.
type Bid struct {
	// BidID stores owner and all other seq numbers.
	// A successful bid becomes a Lease(ID).
	ID v1.BidID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	// State represents the state of the Bid.
	State Bid_State `protobuf:"varint,2,opt,name=state,proto3,enum=akash.market.v2beta1.Bid_State" json:"state" yaml:"state"`
	// Price holds the pricing stated on the Bid.
	Price types.DecCoin `protobuf:"bytes,3,opt,name=price,proto3" json:"price" yaml:"price"`
	// CreatedAt is the block height at which the Bid was created.
	CreatedAt int64 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"createdAt" yaml:"created_at"`
	// ResourceOffer is a list of offers.
	ResourcesOffer ResourcesOffer `protobuf:"bytes,5,rep,name=resources_offer,json=resourcesOffer,proto3,castrepeated=ResourcesOffer" json:"resources_offer" yaml:"resources_offer"`
	// reclamation_window is the reclamation window offered by this provider.
	ReclamationWindow *time.Duration `protobuf:"bytes,6,opt,name=reclamation_window,json=reclamationWindow,proto3,stdduration" json:"reclamation_window,omitempty" yaml:"reclamation_window,omitempty"`
}

func (m *Bid) Reset()      { *m = Bid{} }
func (*Bid) ProtoMessage() {}
func (*Bid) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e525959eb5a7d93, []int{0}
}
func (m *Bid) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Bid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Bid.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Bid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bid.Merge(m, src)
}
func (m *Bid) XXX_Size() int {
	return m.Size()
}
func (m *Bid) XXX_DiscardUnknown() {
	xxx_messageInfo_Bid.DiscardUnknown(m)
}

var xxx_messageInfo_Bid proto.InternalMessageInfo

func (m *Bid) GetID() v1.BidID {
	if m != nil {
		return m.ID
	}
	return v1.BidID{}
}

func (m *Bid) GetState() Bid_State {
	if m != nil {
		return m.State
	}
	return BidStateInvalid
}

func (m *Bid) GetPrice() types.DecCoin {
	if m != nil {
		return m.Price
	}
	return types.DecCoin{}
}

func (m *Bid) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Bid) GetResourcesOffer() ResourcesOffer {
	if m != nil {
		return m.ResourcesOffer
	}
	return nil
}

func (m *Bid) GetReclamationWindow() *time.Duration {
	if m != nil {
		return m.ReclamationWindow
	}
	return nil
}

func init() {
	proto.RegisterEnum("akash.market.v2beta1.Bid_State", Bid_State_name, Bid_State_value)
	proto.RegisterType((*Bid)(nil), "akash.market.v2beta1.Bid")
}

func init() { proto.RegisterFile("akash/market/v2beta1/bid.proto", fileDescriptor_5e525959eb5a7d93) }

var fileDescriptor_5e525959eb5a7d93 = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x4d, 0x4b, 0x1b, 0x4f,
	0x18, 0xcf, 0xe4, 0xcd, 0xbf, 0xe3, 0xbf, 0x1a, 0xb7, 0x56, 0x92, 0x60, 0x77, 0x96, 0xf5, 0x92,
	0x42, 0x99, 0xc5, 0xf4, 0x26, 0xbd, 0xb8, 0xa6, 0x07, 0xa1, 0x60, 0xbb, 0xa5, 0x14, 0x7a, 0x91,
	0xc9, 0xce, 0x98, 0x0e, 0x49, 0x76, 0xc2, 0xee, 0x18, 0xf1, 0x1b, 0x14, 0x4f, 0x85, 0x42, 0xb1,
	0x07, 0x41, 0xf0, 0xd6, 0x4f, 0xe2, 0xd1, 0x63, 0x4f, 0x63, 0x89, 0x97, 0x92, 0x63, 0x3e, 0x41,
	0xd9, 0x99, 0x8d, 0x2f, 0xa9, 0xbd, 0xed, 0xf3, 0x7b, 0x79, 0xf8, 0xcd, 0x8f, 0x67, 0xa1, 0x4d,
	0xba, 0x24, 0xf9, 0xe4, 0xf5, 0x49, 0xdc, 0x65, 0xd2, 0x1b, 0x36, 0xdb, 0x4c, 0x92, 0x0d, 0xaf,
	0xcd, 0x29, 0x1e, 0xc4, 0x42, 0x0a, 0x6b, 0x45, 0xf3, 0xd8, 0xf0, 0x38, 0xe3, 0xeb, 0x2b, 0x1d,
	0xd1, 0x11, 0x5a, 0xe0, 0xa5, 0x5f, 0x46, 0x5b, 0xb7, 0x43, 0x91, 0xf4, 0x45, 0xe2, 0xb5, 0x49,
	0xc2, 0xbc, 0xe1, 0x86, 0x59, 0x15, 0x0a, 0x1e, 0x4d, 0xf9, 0x8e, 0x10, 0x9d, 0x1e, 0xf3, 0xf4,
	0xd4, 0x3e, 0xd8, 0xf7, 0xe8, 0x41, 0x4c, 0x24, 0x17, 0x53, 0xfe, 0xd9, 0x83, 0x59, 0x62, 0x96,
	0x88, 0x83, 0x38, 0x64, 0x89, 0xd8, 0xdf, 0x67, 0x71, 0x26, 0xad, 0xdd, 0x97, 0xde, 0x49, 0xec,
	0x7e, 0x2b, 0xc3, 0x82, 0xcf, 0xa9, 0xf5, 0x0a, 0xe6, 0x39, 0xad, 0x02, 0x07, 0x34, 0x16, 0x9a,
	0xab, 0xf8, 0xfe, 0x33, 0x36, 0xb0, 0xcf, 0xe9, 0x4e, 0xcb, 0x7f, 0x7a, 0xa1, 0x50, 0x6e, 0xa4,
	0x50, 0x7e, 0xa7, 0x35, 0x56, 0x28, 0xcf, 0xe9, 0x44, 0xa1, 0xf9, 0x23, 0xd2, 0xef, 0x6d, 0xba,
	0x9c, 0xba, 0x41, 0x9e, 0x53, 0xeb, 0x0d, 0x2c, 0x25, 0x92, 0x48, 0x56, 0xcd, 0x3b, 0xa0, 0xb1,
	0xd8, 0x44, 0xf8, 0xa1, 0x42, 0xd2, 0x75, 0xf8, 0x5d, 0x2a, 0xf3, 0x6b, 0x63, 0x85, 0x8c, 0x63,
	0xa2, 0xd0, 0xff, 0x66, 0x97, 0x1e, 0xdd, 0xc0, 0xc0, 0xd6, 0x5b, 0x58, 0x1a, 0xc4, 0x3c, 0x64,
	0xd5, 0x82, 0xce, 0xb6, 0x86, 0x4d, 0x6d, 0x38, 0xad, 0x0d, 0x67, 0xb5, 0xe1, 0x16, 0x0b, 0xb7,
	0x05, 0x8f, 0x4c, 0xc2, 0x74, 0xa5, 0xb6, 0xdc, 0xae, 0xd4, 0xa3, 0x1b, 0x18, 0xd8, 0xda, 0x82,
	0x30, 0x8c, 0x19, 0x91, 0x8c, 0xee, 0x11, 0x59, 0x2d, 0x3a, 0xa0, 0x51, 0xf0, 0xdd, 0xb1, 0x42,
	0xf3, 0x19, 0xba, 0x25, 0x27, 0x0a, 0x2d, 0x1b, 0xe7, 0xad, 0xd0, 0x0d, 0x6e, 0x79, 0xeb, 0x1c,
	0xc0, 0xa5, 0x9b, 0xaa, 0xf7, 0x74, 0xd7, 0xd5, 0x92, 0x53, 0x68, 0x2c, 0x34, 0xd7, 0x1f, 0x7e,
	0x72, 0x90, 0x89, 0x77, 0x53, 0xa9, 0xff, 0x3e, 0x6b, 0x72, 0x71, 0x0a, 0x27, 0x1a, 0x1f, 0x2b,
	0x34, 0xbb, 0x75, 0xa2, 0xd0, 0xaa, 0x49, 0x32, 0x43, 0xb8, 0x3f, 0xae, 0x66, 0xed, 0xc1, 0x62,
	0x7c, 0x6f, 0xb6, 0xbe, 0x03, 0x68, 0xc5, 0x2c, 0xec, 0x91, 0xbe, 0x3e, 0x9c, 0xbd, 0x43, 0x1e,
	0x51, 0x71, 0x58, 0x2d, 0xeb, 0x26, 0x6b, 0xd8, 0x1c, 0x18, 0x9e, 0x1e, 0x18, 0x6e, 0x65, 0x07,
	0xe6, 0xef, 0x5e, 0x28, 0x04, 0xc6, 0x0a, 0xad, 0xfd, 0x6d, 0x7e, 0x2e, 0xfa, 0x5c, 0xb2, 0xfe,
	0x40, 0x1e, 0x4d, 0x14, 0x5a, 0x9f, 0x26, 0xfb, 0xb7, 0xca, 0x3d, 0xb9, 0x42, 0x20, 0x58, 0xbe,
	0x23, 0xf9, 0xa0, 0x15, 0xee, 0x57, 0x00, 0x4b, 0xfa, 0x06, 0x2c, 0x07, 0xce, 0xf1, 0x68, 0x48,
	0x7a, 0x9c, 0x56, 0x72, 0xf5, 0xc7, 0xc7, 0xa7, 0xce, 0x92, 0xcf, 0xa9, 0xa6, 0x76, 0x0c, 0x6c,
	0x3d, 0x81, 0x45, 0x31, 0x60, 0x51, 0x05, 0xd4, 0x17, 0x8e, 0x4f, 0x9d, 0x39, 0x9f, 0xd3, 0xdd,
	0x01, 0x8b, 0xac, 0x1a, 0x2c, 0x93, 0x50, 0xf2, 0x21, 0xab, 0xe4, 0xeb, 0x8f, 0x8e, 0x4f, 0x9d,
	0x79, 0x9f, 0xd3, 0x2d, 0x0d, 0xa4, 0x8e, 0x9e, 0x48, 0x64, 0xa5, 0x70, 0xe3, 0x78, 0x2d, 0x12,
	0x99, 0x3a, 0xc2, 0x9e, 0x48, 0x18, 0xad, 0x14, 0x6f, 0x1c, 0xdb, 0x1a, 0xa8, 0x17, 0x3f, 0x9f,
	0xdb, 0xb9, 0xcd, 0xff, 0x4e, 0xce, 0x50, 0xee, 0xf7, 0x19, 0x02, 0xfe, 0xcb, 0x8b, 0x91, 0x0d,
	0x2e, 0x47, 0x36, 0xf8, 0x35, 0xb2, 0xc1, 0x97, 0x6b, 0x3b, 0x77, 0x79, 0x6d, 0xe7, 0x7e, 0x5e,
	0xdb, 0xb9, 0x8f, 0xee, 0xa0, 0xdb, 0xc1, 0xa4, 0x2b, 0x31, 0x65, 0x43, 0xaf, 0x23, 0xbc, 0x48,
	0x50, 0x36, 0xf3, 0x1b, 0xb6, 0xcb, 0xba, 0xd4, 0x17, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6e,
	0x30, 0xdd, 0x75, 0x31, 0x04, 0x00, 0x00,
}

func (this *Bid) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Bid)
	if !ok {
		that2, ok := that.(Bid)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(&that1.ID) {
		return false
	}
	if this.State != that1.State {
		return false
	}
	if !this.Price.Equal(&that1.Price) {
		return false
	}
	if this.CreatedAt != that1.CreatedAt {
		return false
	}
	if len(this.ResourcesOffer) != len(that1.ResourcesOffer) {
		return false
	}
	for i := range this.ResourcesOffer {
		if !this.ResourcesOffer[i].Equal(&that1.ResourcesOffer[i]) {
			return false
		}
	}
	if this.ReclamationWindow != nil && that1.ReclamationWindow != nil {
		if *this.ReclamationWindow != *that1.ReclamationWindow {
			return false
		}
	} else if this.ReclamationWindow != nil {
		return false
	} else if that1.ReclamationWindow != nil {
		return false
	}
	return true
}
func (m *Bid) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Bid) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Bid) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReclamationWindow != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(*m.ReclamationWindow, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(*m.ReclamationWindow):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintBid(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ResourcesOffer) > 0 {
		for iNdEx := len(m.ResourcesOffer) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ResourcesOffer[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBid(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.CreatedAt != 0 {
		i = encodeVarintBid(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.Price.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBid(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.State != 0 {
		i = encodeVarintBid(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBid(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintBid(dAtA []byte, offset int, v uint64) int {
	offset -= sovBid(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Bid) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovBid(uint64(l))
	if m.State != 0 {
		n += 1 + sovBid(uint64(m.State))
	}
	l = m.Price.Size()
	n += 1 + l + sovBid(uint64(l))
	if m.CreatedAt != 0 {
		n += 1 + sovBid(uint64(m.CreatedAt))
	}
	if len(m.ResourcesOffer) > 0 {
		for _, e := range m.ResourcesOffer {
			l = e.Size()
			n += 1 + l + sovBid(uint64(l))
		}
	}
	if m.ReclamationWindow != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(*m.ReclamationWindow)
		n += 1 + l + sovBid(uint64(l))
	}
	return n
}

func sovBid(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBid(x uint64) (n int) {
	return sovBid(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Bid) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBid
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Bid: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Bid: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBid
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= Bid_State(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBid
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourcesOffer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBid
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourcesOffer = append(m.ResourcesOffer, ResourceOffer{})
			if err := m.ResourcesOffer[len(m.ResourcesOffer)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReclamationWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBid
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBid
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBid
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ReclamationWindow == nil {
				m.ReclamationWindow = new(time.Duration)
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(m.ReclamationWindow, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBid(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBid
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBid(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBid
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBid
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBid
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBid
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBid
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBid
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBid        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBid          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBid = fmt.Errorf("proto: unexpected end of group")
)
