// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/market/v2beta1/bidmsg.proto

package v2beta1

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	v1 "pkg.akt.dev/go/node/market/v1"
	v11 "pkg.akt.dev/go/node/types/deposit/v1"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgCreateBid defines an SDK message for creating Bid.
type MsgCreateBid struct {
	ID v1.BidID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	// Price holds the pricing stated on the Bid.
	Price types.DecCoin `protobuf:"bytes,2,opt,name=price,proto3" json:"price" yaml:"price"`
	// Deposit holds the amount of coins to deposit.
	Deposit v11.Deposit `protobuf:"bytes,3,opt,name=deposit,proto3" json:"deposit" yaml:"deposit"`
	// ResourceOffer is a list of resource offers.
	ResourcesOffer ResourcesOffer `protobuf:"bytes,4,rep,name=resources_offer,json=resourcesOffer,proto3,castrepeated=ResourcesOffer" json:"resources_offer" yaml:"resources_offer"`
	// reclamation_window is the reclamation window duration the provider offers.
	// If the order requires reclamation, this must be >= the order's min_window.
	// Nil means the provider does not offer reclamation on this bid.
	ReclamationWindow *time.Duration `protobuf:"bytes,5,opt,name=reclamation_window,json=reclamationWindow,proto3,stdduration" json:"reclamation_window,omitempty" yaml:"reclamation_window,omitempty"`
}

func (m *MsgCreateBid) Reset()         { *m = MsgCreateBid{} }
func (m *MsgCreateBid) String() string { return proto.CompactTextString(m) }
func (*MsgCreateBid) ProtoMessage()    {}
func (*MsgCreateBid) Descriptor() ([]byte, []int) {
	return fileDescriptor_f050bdc39eda64c7, []int{0}
}
func (m *MsgCreateBid) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateBid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateBid.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateBid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateBid.Merge(m, src)
}
func (m *MsgCreateBid) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateBid) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateBid.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateBid proto.InternalMessageInfo

func (m *MsgCreateBid) GetID() v1.BidID {
	if m != nil {
		return m.ID
	}
	return v1.BidID{}
}

func (m *MsgCreateBid) GetPrice() types.DecCoin {
	if m != nil {
		return m.Price
	}
	return types.DecCoin{}
}

func (m *MsgCreateBid) GetDeposit() v11.Deposit {
	if m != nil {
		return m.Deposit
	}
	return v11.Deposit{}
}

func (m *MsgCreateBid) GetResourcesOffer() ResourcesOffer {
	if m != nil {
		return m.ResourcesOffer
	}
	return nil
}

func (m *MsgCreateBid) GetReclamationWindow() *time.Duration {
	if m != nil {
		return m.ReclamationWindow
	}
	return nil
}

// MsgCreateBidResponse defines the Msg/CreateBid response type.
type MsgCreateBidResponse struct {
}

func (m *MsgCreateBidResponse) Reset()         { *m = MsgCreateBidResponse{} }
func (m *MsgCreateBidResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateBidResponse) ProtoMessage()    {}
func (*MsgCreateBidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f050bdc39eda64c7, []int{1}
}
func (m *MsgCreateBidResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateBidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateBidResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateBidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateBidResponse.Merge(m, src)
}
func (m *MsgCreateBidResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateBidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateBidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateBidResponse proto.InternalMessageInfo

// MsgCloseBid defines an SDK message for closing bid.
type MsgCloseBid struct {
	// Id is the unique identifier of the Bid.
	ID     v1.BidID             `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	Reason v1.LeaseClosedReason `protobuf:"varint,2,opt,name=reason,proto3,enum=akash.market.v1.LeaseClosedReason" json:"reason" yaml:"reason"`
}

func (m *MsgCloseBid) Reset()         { *m = MsgCloseBid{} }
func (m *MsgCloseBid) String() string { return proto.CompactTextString(m) }
func (*MsgCloseBid) ProtoMessage()    {}
func (*MsgCloseBid) Descriptor() ([]byte, []int) {
	return fileDescriptor_f050bdc39eda64c7, []int{2}
}
func (m *MsgCloseBid) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCloseBid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCloseBid.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCloseBid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCloseBid.Merge(m, src)
}
func (m *MsgCloseBid) XXX_Size() int {
	return m.Size()
}
func (m *MsgCloseBid) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCloseBid.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCloseBid proto.InternalMessageInfo

func (m *MsgCloseBid) GetID() v1.BidID {
	if m != nil {
		return m.ID
	}
	return v1.BidID{}
}

func (m *MsgCloseBid) GetReason() v1.LeaseClosedReason {
	if m != nil {
		return m.Reason
	}
	return v1.LeaseClosedReasonInvalid
}

// MsgCloseBidResponse defines the Msg/CloseBid response type.
type MsgCloseBidResponse struct {
}

func (m *MsgCloseBidResponse) Reset()         { *m = MsgCloseBidResponse{} }
func (m *MsgCloseBidResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCloseBidResponse) ProtoMessage()    {}
func (*MsgCloseBidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f050bdc39eda64c7, []int{3}
}
func (m *MsgCloseBidResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCloseBidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCloseBidResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCloseBidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCloseBidResponse.Merge(m, src)
}
func (m *MsgCloseBidResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCloseBidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCloseBidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCloseBidResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateBid)(nil), "akash.market.v2beta1.MsgCreateBid")
	proto.RegisterType((*MsgCreateBidResponse)(nil), "akash.market.v2beta1.MsgCreateBidResponse")
	proto.RegisterType((*MsgCloseBid)(nil), "akash.market.v2beta1.MsgCloseBid")
	proto.RegisterType((*MsgCloseBidResponse)(nil), "akash.market.v2beta1.MsgCloseBidResponse")
}

func init() { proto.RegisterFile("akash/market/v2beta1/bidmsg.proto", fileDescriptor_f050bdc39eda64c7) }

var fileDescriptor_f050bdc39eda64c7 = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x3f, 0x6f, 0xd3, 0x4e,
	0x18, 0xc7, 0xe3, 0xf4, 0xcf, 0x4f, 0x3f, 0xb7, 0x04, 0x61, 0x4a, 0x95, 0xfe, 0xc1, 0xd7, 0x5e,
	0x97, 0x22, 0xa1, 0xb3, 0x1a, 0xb6, 0x8a, 0xc9, 0x0d, 0x43, 0x25, 0x50, 0x85, 0x25, 0x54, 0x09,
	0x86, 0xea, 0xe2, 0xbb, 0x9a, 0x53, 0x62, 0x9f, 0xe5, 0x73, 0x52, 0xe5, 0x5d, 0x30, 0xc2, 0x86,
	0xc4, 0xc6, 0xca, 0x9b, 0xc8, 0x82, 0xd4, 0x91, 0xe9, 0x8a, 0x92, 0x05, 0x65, 0xf4, 0x2b, 0x40,
	0xbe, 0x3b, 0xa3, 0x24, 0x2d, 0x1b, 0x9b, 0x9f, 0xe7, 0xf9, 0x3c, 0xdf, 0x7b, 0xfe, 0xc9, 0xf6,
	0x3e, 0xee, 0x62, 0xf1, 0xde, 0x8b, 0x71, 0xd6, 0xa5, 0xb9, 0x37, 0x68, 0x75, 0x68, 0x8e, 0x8f,
	0xbc, 0x0e, 0x23, 0xb1, 0x88, 0x50, 0x9a, 0xf1, 0x9c, 0x3b, 0x1b, 0x0a, 0x41, 0x1a, 0x41, 0x06,
	0xd9, 0xde, 0x88, 0x78, 0xc4, 0x15, 0xe0, 0x95, 0x5f, 0x9a, 0xdd, 0x76, 0x43, 0x2e, 0x62, 0x2e,
	0xbc, 0x0e, 0x16, 0xd4, 0x1b, 0x1c, 0x69, 0xb5, 0x90, 0xb3, 0xc4, 0xc4, 0x9f, 0xdc, 0xf9, 0x5c,
	0x46, 0x05, 0xef, 0x67, 0x21, 0x15, 0xfc, 0xf2, 0x92, 0x66, 0x06, 0xdd, 0x9a, 0x47, 0x55, 0x51,
	0x26, 0x74, 0xa0, 0x43, 0xea, 0x11, 0x42, 0x53, 0x2e, 0x98, 0x02, 0xcc, 0xa7, 0x81, 0x76, 0x16,
	0xf3, 0xf3, 0x61, 0x4a, 0x45, 0x55, 0x67, 0xc4, 0x79, 0xd4, 0xa3, 0x9e, 0xb2, 0x3a, 0xfd, 0x4b,
	0x8f, 0xf4, 0x33, 0x9c, 0x33, 0x6e, 0xea, 0x84, 0xdf, 0x97, 0xed, 0xf5, 0x57, 0x22, 0x3a, 0xc9,
	0x28, 0xce, 0xa9, 0xcf, 0x88, 0xf3, 0xc2, 0xae, 0x33, 0xd2, 0xb4, 0xf6, 0xac, 0xc3, 0xb5, 0xd6,
	0x26, 0x9a, 0x9f, 0xc8, 0x11, 0xf2, 0x19, 0x39, 0x6d, 0xfb, 0x8f, 0x47, 0x12, 0xd4, 0xc6, 0x12,
	0xd4, 0x4f, 0xdb, 0x53, 0x09, 0xea, 0x8c, 0x14, 0x12, 0xfc, 0x3f, 0xc4, 0x71, 0xef, 0x18, 0x32,
	0x02, 0x83, 0x3a, 0x23, 0xce, 0x6b, 0x7b, 0x25, 0xcd, 0x58, 0x48, 0x9b, 0x75, 0xa5, 0xb4, 0x8b,
	0xf4, 0xbc, 0x50, 0xd9, 0x0a, 0x32, 0xf3, 0x42, 0x6d, 0x1a, 0x9e, 0x70, 0x96, 0x68, 0xbd, 0xa9,
	0x04, 0x3a, 0xa5, 0x90, 0x60, 0x5d, 0x8b, 0x29, 0x13, 0x06, 0xda, 0xed, 0xbc, 0xb3, 0xff, 0x33,
	0x8d, 0x37, 0x97, 0x94, 0xa8, 0x6b, 0xca, 0x53, 0x9a, 0xd5, 0x4c, 0x06, 0xa5, 0xac, 0xfa, 0xf4,
	0xf7, 0x8d, 0x6c, 0x95, 0x56, 0x48, 0xd0, 0xd0, 0xc2, 0xc6, 0x01, 0x83, 0x2a, 0xe4, 0x7c, 0xb1,
	0xec, 0xfb, 0x7f, 0xb6, 0x73, 0xa1, 0xd6, 0xd3, 0x5c, 0xde, 0x5b, 0x3a, 0x5c, 0x6b, 0x1d, 0xa0,
	0xbb, 0xce, 0x02, 0x05, 0x06, 0x3e, 0x2b, 0x51, 0xff, 0x8d, 0x99, 0x48, 0xa3, 0x72, 0x0b, 0xe5,
	0x9f, 0x4a, 0xb0, 0xa8, 0x5a, 0x48, 0xb0, 0xa9, 0x8b, 0x58, 0x08, 0xc0, 0xaf, 0x37, 0x8b, 0xe9,
	0x41, 0x23, 0x9b, 0xb3, 0x9d, 0x4f, 0x96, 0xed, 0x64, 0x34, 0xec, 0xe1, 0x58, 0xed, 0xf0, 0xe2,
	0x8a, 0x25, 0x84, 0x5f, 0x35, 0x57, 0xd4, 0x38, 0xb6, 0x90, 0xde, 0x35, 0xaa, 0x76, 0x8d, 0xda,
	0x66, 0xd7, 0xfe, 0xd9, 0x48, 0x02, 0x6b, 0x2a, 0xc1, 0xee, 0xed, 0xe4, 0xa7, 0x3c, 0x66, 0x39,
	0x8d, 0xd3, 0x7c, 0x58, 0x48, 0x70, 0x50, 0x55, 0xf6, 0x77, 0x0a, 0x7e, 0xbc, 0x01, 0x56, 0xf0,
	0x60, 0x06, 0x39, 0x57, 0xc4, 0xf1, 0xf2, 0xaf, 0xcf, 0xa0, 0x06, 0x37, 0xed, 0x8d, 0xd9, 0x73,
	0x0a, 0xa8, 0x48, 0x79, 0x22, 0x28, 0xfc, 0x66, 0xd9, 0x6b, 0x65, 0xa0, 0xc7, 0xc5, 0xbf, 0x3c,
	0xb3, 0x73, 0x7b, 0x35, 0xa3, 0x58, 0xf0, 0x44, 0xdd, 0x59, 0xa3, 0x05, 0x6f, 0x49, 0xbd, 0xa4,
	0x58, 0x50, 0xf5, 0x2c, 0x09, 0x14, 0xe9, 0xef, 0x4c, 0x25, 0x30, 0x59, 0x85, 0x04, 0xf7, 0xaa,
	0x96, 0x4b, 0x1b, 0x06, 0x26, 0x60, 0xba, 0x79, 0x64, 0x3f, 0x9c, 0x29, 0xba, 0x6a, 0xc6, 0x7f,
	0x3e, 0x1a, 0xbb, 0xd6, 0xf5, 0xd8, 0xb5, 0x7e, 0x8e, 0x5d, 0xeb, 0xc3, 0xc4, 0xad, 0x5d, 0x4f,
	0xdc, 0xda, 0x8f, 0x89, 0x5b, 0x7b, 0x0b, 0xd3, 0x6e, 0x84, 0x70, 0x37, 0x47, 0x84, 0x0e, 0xbc,
	0x88, 0x7b, 0x09, 0x27, 0x74, 0xe1, 0x27, 0xd0, 0x59, 0x55, 0xfb, 0x79, 0xf6, 0x3b, 0x00, 0x00,
	0xff, 0xff, 0x8d, 0x0c, 0xbd, 0x28, 0x92, 0x04, 0x00, 0x00,
}

func (m *MsgCreateBid) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateBid) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateBid) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReclamationWindow != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(*m.ReclamationWindow, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(*m.ReclamationWindow):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintBidmsg(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ResourcesOffer) > 0 {
		for iNdEx := len(m.ResourcesOffer) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ResourcesOffer[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBidmsg(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size, err := m.Deposit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBidmsg(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Price.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBidmsg(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBidmsg(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgCreateBidResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateBidResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateBidResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCloseBid) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCloseBid) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCloseBid) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reason != 0 {
		i = encodeVarintBidmsg(dAtA, i, uint64(m.Reason))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBidmsg(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgCloseBidResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCloseBidResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCloseBidResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintBidmsg(dAtA []byte, offset int, v uint64) int {
	offset -= sovBidmsg(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateBid) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovBidmsg(uint64(l))
	l = m.Price.Size()
	n += 1 + l + sovBidmsg(uint64(l))
	l = m.Deposit.Size()
	n += 1 + l + sovBidmsg(uint64(l))
	if len(m.ResourcesOffer) > 0 {
		for _, e := range m.ResourcesOffer {
			l = e.Size()
			n += 1 + l + sovBidmsg(uint64(l))
		}
	}
	if m.ReclamationWindow != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(*m.ReclamationWindow)
		n += 1 + l + sovBidmsg(uint64(l))
	}
	return n
}

func (m *MsgCreateBidResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCloseBid) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovBidmsg(uint64(l))
	if m.Reason != 0 {
		n += 1 + sovBidmsg(uint64(m.Reason))
	}
	return n
}

func (m *MsgCloseBidResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovBidmsg(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBidmsg(x uint64) (n int) {
	return sovBidmsg(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateBid) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBidmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateBid: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateBid: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBidmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBidmsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBidmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBidmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBidmsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBidmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBidmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBidmsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBidmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Deposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourcesOffer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBidmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBidmsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBidmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourcesOffer = append(m.ResourcesOffer, ResourceOffer{})
			if err := m.ResourcesOffer[len(m.ResourcesOffer)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReclamationWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBidmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBidmsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBidmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ReclamationWindow == nil {
				m.ReclamationWindow = new(time.Duration)
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(m.ReclamationWindow, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBidmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBidmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateBidResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBidmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateBidResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateBidResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipBidmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBidmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCloseBid) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBidmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCloseBid: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCloseBid: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBidmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBidmsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBidmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			m.Reason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBidmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reason |= v1.LeaseClosedReason(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBidmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBidmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCloseBidResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBidmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCloseBidResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCloseBidResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipBidmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBidmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBidmsg(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBidmsg
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBidmsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBidmsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBidmsg
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBidmsg
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBidmsg
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBidmsg        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBidmsg          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBidmsg = fmt.Errorf("proto: unexpected end of group")
)
