// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/market/v2beta1/params.proto

package v2beta1

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params is the params for the x/market module.
type Params struct {
	// BidMinDeposit is a parameter for the minimum deposit on a Bid.
	// Deprecated: use BidMinDeposits
	BidMinDeposit types.Coin `protobuf:"bytes,1,opt,name=bid_min_deposit,json=bidMinDeposit,proto3" json:"bid_min_deposit" yaml:"bid_min_deposit"`
	// OrderMaxBids is a parameter for the maximum number of bids in an order.
	OrderMaxBids uint32 `protobuf:"varint,2,opt,name=order_max_bids,json=orderMaxBids,proto3" json:"order_max_bids" yaml:"order_max_bids"`
	// BidMinDeposits is a parameter for the minimum deposits per denom on a Bid.
	BidMinDeposits github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=bid_min_deposits,json=bidMinDeposits,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"bid_min_deposits" yaml:"bid_min_deposits"`
	// min_reclamation_window is the minimum reclamation window duration allowed.
	MinReclamationWindow time.Duration `protobuf:"bytes,4,opt,name=min_reclamation_window,json=minReclamationWindow,proto3,stdduration" json:"min_reclamation_window" yaml:"min_reclamation_window"`
	// max_reclamation_window is the maximum reclamation window duration allowed.
	MaxReclamationWindow time.Duration `protobuf:"bytes,5,opt,name=max_reclamation_window,json=maxReclamationWindow,proto3,stdduration" json:"max_reclamation_window" yaml:"max_reclamation_window"`
	// VolumeOrdersEnabled is the AEP-87 feature flag: it gates volume-group
	// CreateDeployment and, defense-in-depth, CreateBid on volume orders.
	// Default false; flipped by governance.
	VolumeOrdersEnabled bool `protobuf:"varint,6,opt,name=volume_orders_enabled,json=volumeOrdersEnabled,proto3" json:"volume_orders_enabled" yaml:"volume_orders_enabled"`
	// min_volume_reclamation_window is the chain-guaranteed migration-window
	// floor for volume leases.
	MinVolumeReclamationWindow time.Duration `protobuf:"bytes,7,opt,name=min_volume_reclamation_window,json=minVolumeReclamationWindow,proto3,stdduration" json:"min_volume_reclamation_window" yaml:"min_volume_reclamation_window"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_f189866ff050e276, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBidMinDeposit() types.Coin {
	if m != nil {
		return m.BidMinDeposit
	}
	return types.Coin{}
}

func (m *Params) GetOrderMaxBids() uint32 {
	if m != nil {
		return m.OrderMaxBids
	}
	return 0
}

func (m *Params) GetBidMinDeposits() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.BidMinDeposits
	}
	return nil
}

func (m *Params) GetMinReclamationWindow() time.Duration {
	if m != nil {
		return m.MinReclamationWindow
	}
	return 0
}

func (m *Params) GetMaxReclamationWindow() time.Duration {
	if m != nil {
		return m.MaxReclamationWindow
	}
	return 0
}

func (m *Params) GetVolumeOrdersEnabled() bool {
	if m != nil {
		return m.VolumeOrdersEnabled
	}
	return false
}

func (m *Params) GetMinVolumeReclamationWindow() time.Duration {
	if m != nil {
		return m.MinVolumeReclamationWindow
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "akash.market.v2beta1.Params")
}

func init() { proto.RegisterFile("akash/market/v2beta1/params.proto", fileDescriptor_f189866ff050e276) }

var fileDescriptor_f189866ff050e276 = []byte{
	// 577 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xbf, 0x6f, 0xd3, 0x4e,
	0x1c, 0xcd, 0x7d, 0xfb, 0xa5, 0x54, 0xa6, 0x2d, 0xc8, 0x4d, 0x4b, 0x88, 0xa8, 0x2f, 0x58, 0x0c,
	0x59, 0xb8, 0x53, 0xcb, 0x06, 0x4c, 0x6e, 0x19, 0x2b, 0x8a, 0x07, 0x90, 0x58, 0xac, 0x73, 0xee,
	0x70, 0x4f, 0x89, 0x7d, 0xc1, 0xe7, 0xa4, 0xe9, 0x0e, 0x3b, 0x12, 0x0c, 0xfc, 0x0d, 0x2c, 0x6c,
	0xfc, 0x0d, 0x1d, 0x3b, 0x32, 0x5d, 0x91, 0xb3, 0x65, 0xf4, 0x5f, 0x80, 0xec, 0x73, 0xd4, 0xfc,
	0x70, 0x0b, 0x53, 0x7e, 0xbc, 0xf7, 0x79, 0x9f, 0xf7, 0x79, 0xcf, 0xb2, 0xf1, 0x88, 0x74, 0x89,
	0x3c, 0xc1, 0x21, 0x89, 0xbb, 0x2c, 0xc1, 0xc3, 0x7d, 0x9f, 0x25, 0x64, 0x0f, 0xf7, 0x49, 0x4c,
	0x42, 0x89, 0xfa, 0xb1, 0x48, 0x84, 0x59, 0x2f, 0x28, 0x48, 0x53, 0x50, 0x49, 0x69, 0xd6, 0x03,
	0x11, 0x88, 0x82, 0x80, 0xf3, 0x6f, 0x9a, 0xdb, 0xb4, 0x3a, 0x42, 0x86, 0x42, 0x62, 0x9f, 0x48,
	0x86, 0x87, 0x7b, 0x5a, 0xad, 0x23, 0x78, 0x34, 0xc5, 0x03, 0x21, 0x82, 0x1e, 0xc3, 0xc5, 0x2f,
	0x7f, 0xf0, 0x1e, 0xd3, 0x41, 0x4c, 0x12, 0x2e, 0x4a, 0xdc, 0xfe, 0xb2, 0x66, 0xac, 0x1e, 0x17,
	0xcb, 0xcd, 0x4f, 0xc0, 0xb8, 0xeb, 0x73, 0xea, 0x85, 0x3c, 0xf2, 0x28, 0xeb, 0x0b, 0xc9, 0x93,
	0x06, 0x68, 0x81, 0xf6, 0x9d, 0xfd, 0x07, 0x48, 0x6f, 0x41, 0xf9, 0x16, 0x54, 0x6e, 0x41, 0x07,
	0x82, 0x47, 0x8e, 0x73, 0xae, 0x60, 0x2d, 0x55, 0x70, 0xc3, 0xe1, 0xf4, 0x88, 0x47, 0x87, 0x7a,
	0x6e, 0xa2, 0xe0, 0xa2, 0x54, 0xa6, 0xe0, 0xce, 0x19, 0x09, 0x7b, 0xcf, 0xec, 0x05, 0xc0, 0x76,
	0x37, 0xfc, 0xd9, 0x59, 0x93, 0x18, 0x9b, 0x22, 0xa6, 0x2c, 0xf6, 0x42, 0x32, 0xf2, 0x7c, 0x4e,
	0x65, 0xe3, 0xbf, 0x16, 0x68, 0x6f, 0x38, 0xcf, 0x53, 0x05, 0xd7, 0x5f, 0xe5, 0xc8, 0x11, 0x19,
	0x39, 0x9c, 0xca, 0x89, 0x82, 0x0b, 0xcc, 0x4c, 0xc1, 0x6d, 0xbd, 0x64, 0xfe, 0x7f, 0xdb, 0x5d,
	0x17, 0x33, 0x83, 0xe6, 0x4f, 0x60, 0xdc, 0x5b, 0xb0, 0x21, 0x1b, 0x2b, 0xad, 0x95, 0x9b, 0x6f,
	0xfd, 0x50, 0xde, 0xba, 0x39, 0x77, 0x6b, 0x6e, 0x63, 0x49, 0x2c, 0x53, 0xf0, 0x7e, 0xe5, 0xb5,
	0xd2, 0xfe, 0x7e, 0x09, 0xdb, 0x01, 0x4f, 0x4e, 0x06, 0x3e, 0xea, 0x88, 0x10, 0x97, 0xfd, 0xe9,
	0x8f, 0x27, 0x92, 0x76, 0x71, 0x72, 0xd6, 0x67, 0xb2, 0xd8, 0x28, 0xdd, 0xcd, 0xb9, 0x68, 0xa4,
	0xf9, 0x15, 0x18, 0x3b, 0xb9, 0x5a, 0xcc, 0x3a, 0x3d, 0x12, 0x16, 0x45, 0x7a, 0xa7, 0x3c, 0xa2,
	0xe2, 0xb4, 0xf1, 0x7f, 0x59, 0x95, 0x2e, 0x1c, 0x4d, 0x0b, 0x47, 0x87, 0x65, 0xe1, 0xce, 0x41,
	0x6e, 0x7f, 0xa2, 0xe0, 0x35, 0x02, 0x99, 0x82, 0xbb, 0xda, 0x72, 0x35, 0x6e, 0x7f, 0xbb, 0x84,
	0xc0, 0xad, 0x87, 0x3c, 0x72, 0xaf, 0xb0, 0xb7, 0x05, 0xa4, 0x6d, 0x91, 0x51, 0x95, 0xad, 0x5b,
	0xff, 0x6e, 0xab, 0x52, 0x60, 0xc6, 0x56, 0x25, 0x3e, 0xb5, 0x45, 0x46, 0xcb, 0xb6, 0x3e, 0x02,
	0x63, 0x7b, 0x28, 0x7a, 0x83, 0x90, 0x79, 0x45, 0xfd, 0xd2, 0x63, 0x11, 0xf1, 0x7b, 0x8c, 0x36,
	0x56, 0x5b, 0xa0, 0xbd, 0xe6, 0x1c, 0xa7, 0x0a, 0x6e, 0xbd, 0x29, 0x08, 0xc5, 0x73, 0x25, 0x5f,
	0x6a, 0x78, 0xa2, 0x60, 0xf5, 0x5c, 0xa6, 0xe0, 0x43, 0x6d, 0xa6, 0x12, 0xb6, 0xdd, 0xad, 0xe1,
	0xb2, 0x9a, 0xf9, 0x03, 0x18, 0xbb, 0x79, 0xa6, 0xe5, 0x4c, 0x45, 0x48, 0xb7, 0xff, 0x16, 0xd2,
	0xeb, 0x32, 0xa4, 0x9b, 0x75, 0x32, 0x05, 0x1f, 0x5f, 0x55, 0x78, 0x2d, 0x4d, 0x47, 0xd6, 0x0c,
	0x79, 0xa4, 0x6f, 0x5f, 0x0a, 0xce, 0x79, 0x71, 0x9e, 0x5a, 0xe0, 0x22, 0xb5, 0xc0, 0xef, 0xd4,
	0x02, 0x9f, 0xc7, 0x56, 0xed, 0x62, 0x6c, 0xd5, 0x7e, 0x8d, 0xad, 0xda, 0x3b, 0xbb, 0xdf, 0x0d,
	0x10, 0xe9, 0x26, 0x88, 0xb2, 0x21, 0x0e, 0x04, 0x8e, 0x04, 0x65, 0x0b, 0x2f, 0x33, 0x7f, 0xb5,
	0xf0, 0xff, 0xf4, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x23, 0x4b, 0x01, 0xeb, 0x04, 0x00,
	0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MinVolumeReclamationWindow, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MinVolumeReclamationWindow):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x3a
	if m.VolumeOrdersEnabled {
		i--
		if m.VolumeOrdersEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MaxReclamationWindow, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxReclamationWindow):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x2a
	n3, err3 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MinReclamationWindow, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MinReclamationWindow):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintParams(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x22
	if len(m.BidMinDeposits) > 0 {
		for iNdEx := len(m.BidMinDeposits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BidMinDeposits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.OrderMaxBids != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.OrderMaxBids))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.BidMinDeposit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BidMinDeposit.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.OrderMaxBids != 0 {
		n += 1 + sovParams(uint64(m.OrderMaxBids))
	}
	if len(m.BidMinDeposits) > 0 {
		for _, e := range m.BidMinDeposits {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MinReclamationWindow)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxReclamationWindow)
	n += 1 + l + sovParams(uint64(l))
	if m.VolumeOrdersEnabled {
		n += 2
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MinVolumeReclamationWindow)
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BidMinDeposit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BidMinDeposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderMaxBids", wireType)
			}
			m.OrderMaxBids = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrderMaxBids |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BidMinDeposits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BidMinDeposits = append(m.BidMinDeposits, types.Coin{})
			if err := m.BidMinDeposits[len(m.BidMinDeposits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinReclamationWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MinReclamationWindow, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxReclamationWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MaxReclamationWindow, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VolumeOrdersEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.VolumeOrdersEnabled = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinVolumeReclamationWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MinVolumeReclamationWindow, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
