// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/deployment/v1/event.proto

package v1

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventDeploymentCreated event is triggered when deployment is created on chain.
// It contains all the information required to identify a deployment.
type EventDeploymentCreated struct {
	// ID is the unique identifier of the deployment.
	ID DeploymentID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	// Hash is an hashed representation of the deployment.
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash" yaml:"hash"`
}

func (m *EventDeploymentCreated) Reset()         { *m = EventDeploymentCreated{} }
func (m *EventDeploymentCreated) String() string { return proto.CompactTextString(m) }
func (*EventDeploymentCreated) ProtoMessage()    {}
func (*EventDeploymentCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af18b536d600791, []int{0}
}
func (m *EventDeploymentCreated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventDeploymentCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventDeploymentCreated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventDeploymentCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDeploymentCreated.Merge(m, src)
}
func (m *EventDeploymentCreated) XXX_Size() int {
	return m.Size()
}
func (m *EventDeploymentCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDeploymentCreated.DiscardUnknown(m)
}

var xxx_messageInfo_EventDeploymentCreated proto.InternalMessageInfo

func (m *EventDeploymentCreated) GetID() DeploymentID {
	if m != nil {
		return m.ID
	}
	return DeploymentID{}
}

func (m *EventDeploymentCreated) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

// EventDeploymentUpdated is triggered when deployment is updated on chain.
// It contains all the information required to identify a deployment.
type EventDeploymentUpdated struct {
	// ID is the unique identifier of the deployment.
	ID DeploymentID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	// Hash is an hashed representation of the deployment.
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash" yaml:"hash"`
}

func (m *EventDeploymentUpdated) Reset()         { *m = EventDeploymentUpdated{} }
func (m *EventDeploymentUpdated) String() string { return proto.CompactTextString(m) }
func (*EventDeploymentUpdated) ProtoMessage()    {}
func (*EventDeploymentUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af18b536d600791, []int{1}
}
func (m *EventDeploymentUpdated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventDeploymentUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventDeploymentUpdated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventDeploymentUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDeploymentUpdated.Merge(m, src)
}
func (m *EventDeploymentUpdated) XXX_Size() int {
	return m.Size()
}
func (m *EventDeploymentUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDeploymentUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_EventDeploymentUpdated proto.InternalMessageInfo

func (m *EventDeploymentUpdated) GetID() DeploymentID {
	if m != nil {
		return m.ID
	}
	return DeploymentID{}
}

func (m *EventDeploymentUpdated) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

// EventDeploymentClosed is triggered when deployment is closed on chain.
// It contains all the information required to identify a deployment.
type EventDeploymentClosed struct {
	// ID is the unique identifier of the deployment.
	ID DeploymentID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
}

func (m *EventDeploymentClosed) Reset()         { *m = EventDeploymentClosed{} }
func (m *EventDeploymentClosed) String() string { return proto.CompactTextString(m) }
func (*EventDeploymentClosed) ProtoMessage()    {}
func (*EventDeploymentClosed) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af18b536d600791, []int{2}
}
func (m *EventDeploymentClosed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventDeploymentClosed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventDeploymentClosed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventDeploymentClosed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDeploymentClosed.Merge(m, src)
}
func (m *EventDeploymentClosed) XXX_Size() int {
	return m.Size()
}
func (m *EventDeploymentClosed) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDeploymentClosed.DiscardUnknown(m)
}

var xxx_messageInfo_EventDeploymentClosed proto.InternalMessageInfo

func (m *EventDeploymentClosed) GetID() DeploymentID {
	if m != nil {
		return m.ID
	}
	return DeploymentID{}
}

// EventGroupStarted is triggered when deployment group is started.
// It contains all the information required to identify a group.
type EventGroupStarted struct {
	// ID is the unique identifier of the group.
	ID GroupID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
}

func (m *EventGroupStarted) Reset()         { *m = EventGroupStarted{} }
func (m *EventGroupStarted) String() string { return proto.CompactTextString(m) }
func (*EventGroupStarted) ProtoMessage()    {}
func (*EventGroupStarted) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af18b536d600791, []int{3}
}
func (m *EventGroupStarted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventGroupStarted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventGroupStarted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventGroupStarted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventGroupStarted.Merge(m, src)
}
func (m *EventGroupStarted) XXX_Size() int {
	return m.Size()
}
func (m *EventGroupStarted) XXX_DiscardUnknown() {
	xxx_messageInfo_EventGroupStarted.DiscardUnknown(m)
}

var xxx_messageInfo_EventGroupStarted proto.InternalMessageInfo

func (m *EventGroupStarted) GetID() GroupID {
	if m != nil {
		return m.ID
	}
	return GroupID{}
}

// EventGroupPaused is triggered when deployment group is paused.
// It contains all the information required to identify a group.
type EventGroupPaused struct {
	// ID is the unique identifier of the group.
	ID GroupID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
}

func (m *EventGroupPaused) Reset()         { *m = EventGroupPaused{} }
func (m *EventGroupPaused) String() string { return proto.CompactTextString(m) }
func (*EventGroupPaused) ProtoMessage()    {}
func (*EventGroupPaused) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af18b536d600791, []int{4}
}
func (m *EventGroupPaused) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventGroupPaused) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventGroupPaused.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventGroupPaused) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventGroupPaused.Merge(m, src)
}
func (m *EventGroupPaused) XXX_Size() int {
	return m.Size()
}
func (m *EventGroupPaused) XXX_DiscardUnknown() {
	xxx_messageInfo_EventGroupPaused.DiscardUnknown(m)
}

var xxx_messageInfo_EventGroupPaused proto.InternalMessageInfo

func (m *EventGroupPaused) GetID() GroupID {
	if m != nil {
		return m.ID
	}
	return GroupID{}
}

// EventGroupClosed is triggered when deployment group is closed.
// It contains all the information required to identify a group.
type EventGroupClosed struct {
	// ID is the unique identifier of the group.
	ID GroupID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
}

func (m *EventGroupClosed) Reset()         { *m = EventGroupClosed{} }
func (m *EventGroupClosed) String() string { return proto.CompactTextString(m) }
func (*EventGroupClosed) ProtoMessage()    {}
func (*EventGroupClosed) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af18b536d600791, []int{5}
}
func (m *EventGroupClosed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventGroupClosed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventGroupClosed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventGroupClosed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventGroupClosed.Merge(m, src)
}
func (m *EventGroupClosed) XXX_Size() int {
	return m.Size()
}
func (m *EventGroupClosed) XXX_DiscardUnknown() {
	xxx_messageInfo_EventGroupClosed.DiscardUnknown(m)
}

var xxx_messageInfo_EventGroupClosed proto.InternalMessageInfo

func (m *EventGroupClosed) GetID() GroupID {
	if m != nil {
		return m.ID
	}
	return GroupID{}
}

// EventVolumeAdopted is triggered when a new volume group adopts a dead
// retained volume, transferring the vid's data continuity to the new group.
type EventVolumeAdopted struct {
	// ID is the unique identifier of the new (adopting) volume group.
	ID GroupID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	// Adopted references the dead retained volume being adopted.
	Adopted VolumeRef `protobuf:"bytes,2,opt,name=adopted,proto3" json:"adopted" yaml:"adopted"`
	// Vid is the data-continuity label shared by both volumes.
	Vid string `protobuf:"bytes,3,opt,name=vid,proto3" json:"vid" yaml:"vid"`
}

func (m *EventVolumeAdopted) Reset()         { *m = EventVolumeAdopted{} }
func (m *EventVolumeAdopted) String() string { return proto.CompactTextString(m) }
func (*EventVolumeAdopted) ProtoMessage()    {}
func (*EventVolumeAdopted) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af18b536d600791, []int{6}
}
func (m *EventVolumeAdopted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventVolumeAdopted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventVolumeAdopted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventVolumeAdopted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventVolumeAdopted.Merge(m, src)
}
func (m *EventVolumeAdopted) XXX_Size() int {
	return m.Size()
}
func (m *EventVolumeAdopted) XXX_DiscardUnknown() {
	xxx_messageInfo_EventVolumeAdopted.DiscardUnknown(m)
}

var xxx_messageInfo_EventVolumeAdopted proto.InternalMessageInfo

func (m *EventVolumeAdopted) GetID() GroupID {
	if m != nil {
		return m.ID
	}
	return GroupID{}
}

func (m *EventVolumeAdopted) GetAdopted() VolumeRef {
	if m != nil {
		return m.Adopted
	}
	return VolumeRef{}
}

func (m *EventVolumeAdopted) GetVid() string {
	if m != nil {
		return m.Vid
	}
	return ""
}

func init() {
	proto.RegisterType((*EventDeploymentCreated)(nil), "akash.deployment.v1.EventDeploymentCreated")
	proto.RegisterType((*EventDeploymentUpdated)(nil), "akash.deployment.v1.EventDeploymentUpdated")
	proto.RegisterType((*EventDeploymentClosed)(nil), "akash.deployment.v1.EventDeploymentClosed")
	proto.RegisterType((*EventGroupStarted)(nil), "akash.deployment.v1.EventGroupStarted")
	proto.RegisterType((*EventGroupPaused)(nil), "akash.deployment.v1.EventGroupPaused")
	proto.RegisterType((*EventGroupClosed)(nil), "akash.deployment.v1.EventGroupClosed")
	proto.RegisterType((*EventVolumeAdopted)(nil), "akash.deployment.v1.EventVolumeAdopted")
}

func init() { proto.RegisterFile("akash/deployment/v1/event.proto", fileDescriptor_8af18b536d600791) }

var fileDescriptor_8af18b536d600791 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x86, 0x33, 0xb9, 0x17, 0xe5, 0x4e, 0x45, 0x34, 0x7a, 0xb5, 0x14, 0xcd, 0xa4, 0x41, 0xb0,
	0x20, 0x24, 0xb4, 0xee, 0xea, 0xca, 0x58, 0x91, 0xe2, 0xa6, 0x44, 0x74, 0xa1, 0xab, 0x91, 0x99,
	0xa6, 0xa1, 0x69, 0x27, 0x24, 0x69, 0xa0, 0x6f, 0xe1, 0x0b, 0x08, 0x3e, 0x4e, 0x97, 0x5d, 0xba,
	0x1a, 0x24, 0xdd, 0x48, 0xc0, 0x4d, 0x9e, 0x40, 0x66, 0x26, 0xb5, 0x55, 0xb2, 0x11, 0xac, 0xdc,
	0x5d, 0xcf, 0x99, 0xff, 0xfc, 0xdf, 0xdf, 0x93, 0x61, 0x20, 0xc2, 0x73, 0x9c, 0xce, 0x5c, 0x42,
	0xe3, 0x88, 0xad, 0x17, 0x74, 0x99, 0xb9, 0x79, 0xdf, 0xa5, 0x39, 0x5d, 0x66, 0x4e, 0x9c, 0xb0,
	0x8c, 0x19, 0x77, 0xa4, 0xc0, 0x39, 0x08, 0x9c, 0xbc, 0xdf, 0xb9, 0x1b, 0xb0, 0x80, 0xc9, 0x73,
	0x57, 0xfc, 0x52, 0xd2, 0xce, 0xa3, 0x26, 0xaf, 0xa3, 0x41, 0xa5, 0x6a, 0x24, 0x06, 0x09, 0x5b,
	0xc5, 0xb5, 0xc0, 0x6a, 0x12, 0xe4, 0x2c, 0x5a, 0x2d, 0xa8, 0x52, 0xd8, 0x9f, 0x01, 0xbc, 0xf7,
	0x52, 0x64, 0x1c, 0xfd, 0xd2, 0xbc, 0x48, 0x28, 0xce, 0x28, 0x31, 0x26, 0x50, 0x0f, 0x49, 0x1b,
	0x58, 0xa0, 0xd7, 0x1a, 0x74, 0x9d, 0x86, 0xec, 0xce, 0x61, 0x66, 0x3c, 0xf2, 0x1e, 0x6e, 0x38,
	0xd2, 0x0a, 0x8e, 0xf4, 0xf1, 0xa8, 0xe4, 0x48, 0x0f, 0x49, 0xc5, 0xd1, 0xc5, 0x1a, 0x2f, 0xa2,
	0xa1, 0x1d, 0x12, 0xdb, 0xd7, 0x43, 0x62, 0x3c, 0x81, 0xe7, 0x33, 0x9c, 0xce, 0xda, 0xba, 0x05,
	0x7a, 0x37, 0xbc, 0xfb, 0x25, 0x47, 0xb2, 0xae, 0x38, 0x6a, 0x29, 0xa1, 0xa8, 0x6c, 0x5f, 0x36,
	0x87, 0xe7, 0xdf, 0xbf, 0x20, 0xd0, 0x94, 0xef, 0x6d, 0x4c, 0xae, 0x4e, 0x3e, 0x06, 0x2f, 0xff,
	0x5c, 0x5f, 0xc4, 0xd2, 0x53, 0xa4, 0xab, 0x81, 0x53, 0x78, 0x5b, 0x02, 0x5f, 0x89, 0xcf, 0xfc,
	0x26, 0xc3, 0x89, 0x58, 0xc5, 0xeb, 0x23, 0xd8, 0x83, 0x46, 0x98, 0x94, 0xff, 0x0d, 0x87, 0xc2,
	0x5b, 0x07, 0xce, 0x04, 0xaf, 0xd2, 0xff, 0x80, 0xa9, 0x57, 0x77, 0x02, 0xcc, 0x0f, 0x00, 0x0d,
	0xc9, 0x79, 0x27, 0x2f, 0xff, 0x73, 0xc2, 0xe2, 0x7f, 0xbd, 0x37, 0xe3, 0x03, 0xbc, 0x8e, 0x95,
	0xaf, 0xbc, 0x40, 0xad, 0x81, 0xd9, 0xe8, 0xa8, 0x12, 0xf8, 0x74, 0xea, 0x75, 0x85, 0x67, 0xc9,
	0xd1, 0x7e, 0xac, 0xe2, 0xe8, 0xa6, 0xb2, 0xac, 0x1b, 0xb6, 0xbf, 0x3f, 0x32, 0x1e, 0xc3, 0xb3,
	0x3c, 0x24, 0xed, 0x33, 0x0b, 0xf4, 0x2e, 0xbc, 0xcb, 0x92, 0x23, 0x51, 0x56, 0x1c, 0x41, 0x35,
	0x90, 0x8b, 0x10, 0xa2, 0xa5, 0xfe, 0xaf, 0xf7, 0x6c, 0x53, 0x98, 0x60, 0x5b, 0x98, 0xe0, 0x5b,
	0x61, 0x82, 0x4f, 0x3b, 0x53, 0xdb, 0xee, 0x4c, 0xed, 0xeb, 0xce, 0xd4, 0xde, 0x77, 0xe3, 0x79,
	0xe0, 0xe0, 0x79, 0xe6, 0x10, 0x9a, 0xbb, 0x01, 0x73, 0x97, 0x8c, 0xd0, 0xdf, 0x1f, 0x88, 0x8f,
	0xd7, 0xe4, 0xd3, 0xf0, 0xf4, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8a, 0xae, 0x34, 0xfd, 0xd1,
	0x04, 0x00, 0x00,
}

func (this *EventDeploymentCreated) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventDeploymentCreated)
	if !ok {
		that2, ok := that.(EventDeploymentCreated)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(&that1.ID) {
		return false
	}
	if !bytes.Equal(this.Hash, that1.Hash) {
		return false
	}
	return true
}
func (this *EventDeploymentUpdated) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventDeploymentUpdated)
	if !ok {
		that2, ok := that.(EventDeploymentUpdated)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(&that1.ID) {
		return false
	}
	if !bytes.Equal(this.Hash, that1.Hash) {
		return false
	}
	return true
}
func (this *EventDeploymentClosed) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventDeploymentClosed)
	if !ok {
		that2, ok := that.(EventDeploymentClosed)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(&that1.ID) {
		return false
	}
	return true
}
func (this *EventGroupStarted) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventGroupStarted)
	if !ok {
		that2, ok := that.(EventGroupStarted)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(&that1.ID) {
		return false
	}
	return true
}
func (this *EventGroupPaused) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventGroupPaused)
	if !ok {
		that2, ok := that.(EventGroupPaused)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(&that1.ID) {
		return false
	}
	return true
}
func (this *EventGroupClosed) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventGroupClosed)
	if !ok {
		that2, ok := that.(EventGroupClosed)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(&that1.ID) {
		return false
	}
	return true
}
func (this *EventVolumeAdopted) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EventVolumeAdopted)
	if !ok {
		that2, ok := that.(EventVolumeAdopted)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(&that1.ID) {
		return false
	}
	if !this.Adopted.Equal(&that1.Adopted) {
		return false
	}
	if this.Vid != that1.Vid {
		return false
	}
	return true
}
func (m *EventDeploymentCreated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventDeploymentCreated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventDeploymentCreated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventDeploymentUpdated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventDeploymentUpdated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventDeploymentUpdated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventDeploymentClosed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventDeploymentClosed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventDeploymentClosed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventGroupStarted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventGroupStarted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventGroupStarted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventGroupPaused) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventGroupPaused) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventGroupPaused) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventGroupClosed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventGroupClosed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventGroupClosed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventVolumeAdopted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventVolumeAdopted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventVolumeAdopted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Vid) > 0 {
		i -= len(m.Vid)
		copy(dAtA[i:], m.Vid)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Vid)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Adopted.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventDeploymentCreated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EventDeploymentUpdated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EventDeploymentClosed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventGroupStarted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventGroupPaused) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventGroupClosed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventVolumeAdopted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = m.Adopted.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = len(m.Vid)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventDeploymentCreated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventDeploymentCreated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventDeploymentCreated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventDeploymentUpdated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventDeploymentUpdated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventDeploymentUpdated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventDeploymentClosed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventDeploymentClosed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventDeploymentClosed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventGroupStarted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventGroupStarted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventGroupStarted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventGroupPaused) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventGroupPaused: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventGroupPaused: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventGroupClosed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventGroupClosed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventGroupClosed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventVolumeAdopted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventVolumeAdopted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventVolumeAdopted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Adopted", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Adopted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
