// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/deployment/v1/volume.proto

package v1

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ReclaimPolicy declares what happens to the volume's data after its
// lease closes.
type VolumePolicy_ReclaimPolicy int32

const (
	// Prefix should start with 0 in enum. So declaring dummy state.
	VolumeReclaimInvalid VolumePolicy_ReclaimPolicy = 0
	// retain keeps the data adoptable for the retention window after close.
	VolumeReclaimRetain VolumePolicy_ReclaimPolicy = 1
	// delete destroys the data immediately after close and detach.
	VolumeReclaimDelete VolumePolicy_ReclaimPolicy = 2
)

var VolumePolicy_ReclaimPolicy_name = map[int32]string{
	0: "invalid",
	1: "retain",
	2: "delete",
}

var VolumePolicy_ReclaimPolicy_value = map[string]int32{
	"invalid": 0,
	"retain":  1,
	"delete":  2,
}

func (x VolumePolicy_ReclaimPolicy) String() string {
	return proto.EnumName(VolumePolicy_ReclaimPolicy_name, int32(x))
}

func (VolumePolicy_ReclaimPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0bf9664fe5f0b80a, []int{1, 0}
}

// VolumeRef addresses one Storage entry of a storage-only ("volume") group.
type VolumeRef struct {
	// Owner is the account bech32 address of the user who owns the volume group.
	// It is a string representing a valid bech32 account address.
	//
	// Example:
	//   "akash1..."
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner" yaml:"owner"`
	// Dseq (deployment sequence number) of the volume deployment.
	DSeq uint64 `protobuf:"varint,2,opt,name=dseq,proto3" json:"dseq" yaml:"dseq"`
	// Gseq (group sequence number) of the volume group. Always 1 in v1:
	// a deployment containing a volume group contains only that group.
	GSeq uint32 `protobuf:"varint,3,opt,name=gseq,proto3" json:"gseq" yaml:"gseq"`
	// Name is the Storage.Name of the single storage entry in the volume group.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name" yaml:"name"`
}

func (m *VolumeRef) Reset()      { *m = VolumeRef{} }
func (*VolumeRef) ProtoMessage() {}
func (*VolumeRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf9664fe5f0b80a, []int{0}
}
func (m *VolumeRef) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VolumeRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VolumeRef.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VolumeRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeRef.Merge(m, src)
}
func (m *VolumeRef) XXX_Size() int {
	return m.Size()
}
func (m *VolumeRef) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeRef.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeRef proto.InternalMessageInfo

func (m *VolumeRef) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *VolumeRef) GetDSeq() uint64 {
	if m != nil {
		return m.DSeq
	}
	return 0
}

func (m *VolumeRef) GetGSeq() uint32 {
	if m != nil {
		return m.GSeq
	}
	return 0
}

func (m *VolumeRef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// VolumePolicy marks a group as a storage-only volume group and carries its
// lifecycle contract. Presence of this message IS the volume discriminator.
type VolumePolicy struct {
	// Vid is the tenant-chosen data-continuity label (DNS-label grammar,
	// [a-z0-9]([-a-z0-9]{0,61}[a-z0-9])?). Typed field -- NEVER a storage
	// attribute (attributes flow into AttributesSubsetOf provider matching
	// and would make the order unbiddable).
	Vid string `protobuf:"bytes,1,opt,name=vid,proto3" json:"vid" yaml:"vid"`
	// Reclaim declares the post-close fate of the volume's data.
	Reclaim VolumePolicy_ReclaimPolicy `protobuf:"varint,2,opt,name=reclaim,proto3,enum=akash.deployment.v1.VolumePolicy_ReclaimPolicy" json:"reclaim" yaml:"reclaim"`
	// Retention is the post-close window the provider must keep the data
	// adoptable. Bounded by deployment Params.MaxVolumeRetention; priced into
	// the bid. GC deadline is chain-computable: closedLease.ClosedAt + retention.
	Retention time.Duration `protobuf:"bytes,3,opt,name=retention,proto3,stdduration" json:"retention" yaml:"retention"`
	// MaxAttachments bounds concurrent attached compute leases.
	// Validation forces 1 in v1 (RWO); the field exists so RWX is additive.
	MaxAttachments uint32 `protobuf:"varint,4,opt,name=max_attachments,json=maxAttachments,proto3" json:"max_attachments" yaml:"max_attachments"`
	// MaxReplicas declares how many replica volumes the tenant may point at
	// this volume (replica_of backrefs). >0 obliges the winning provider to
	// serve replication export traffic -- a bid-time-known, priced duty.
	MaxReplicas uint32 `protobuf:"varint,5,opt,name=max_replicas,json=maxReplicas,proto3" json:"max_replicas" yaml:"max_replicas"`
	// Adopt, when set, makes this volume an ADOPTION of a dead retained volume:
	// same owner, same vid, group closed, within its retention window. Bids are
	// chain-gated to the provider of adopt's last closed lease.
	Adopt *VolumeRef `protobuf:"bytes,6,opt,name=adopt,proto3" json:"adopt,omitempty" yaml:"adopt,omitempty"`
	// ReplicaOf, when set, declares this volume a replica of the named volume
	// (same owner). Drives data-plane authorization on both ends.
	ReplicaOf *VolumeRef `protobuf:"bytes,7,opt,name=replica_of,json=replicaOf,proto3" json:"replica_of,omitempty" yaml:"replica_of,omitempty"`
}

func (m *VolumePolicy) Reset()         { *m = VolumePolicy{} }
func (m *VolumePolicy) String() string { return proto.CompactTextString(m) }
func (*VolumePolicy) ProtoMessage()    {}
func (*VolumePolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf9664fe5f0b80a, []int{1}
}
func (m *VolumePolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VolumePolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VolumePolicy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VolumePolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumePolicy.Merge(m, src)
}
func (m *VolumePolicy) XXX_Size() int {
	return m.Size()
}
func (m *VolumePolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumePolicy.DiscardUnknown(m)
}

var xxx_messageInfo_VolumePolicy proto.InternalMessageInfo

func (m *VolumePolicy) GetVid() string {
	if m != nil {
		return m.Vid
	}
	return ""
}

func (m *VolumePolicy) GetReclaim() VolumePolicy_ReclaimPolicy {
	if m != nil {
		return m.Reclaim
	}
	return VolumeReclaimInvalid
}

func (m *VolumePolicy) GetRetention() time.Duration {
	if m != nil {
		return m.Retention
	}
	return 0
}

func (m *VolumePolicy) GetMaxAttachments() uint32 {
	if m != nil {
		return m.MaxAttachments
	}
	return 0
}

func (m *VolumePolicy) GetMaxReplicas() uint32 {
	if m != nil {
		return m.MaxReplicas
	}
	return 0
}

func (m *VolumePolicy) GetAdopt() *VolumeRef {
	if m != nil {
		return m.Adopt
	}
	return nil
}

func (m *VolumePolicy) GetReplicaOf() *VolumeRef {
	if m != nil {
		return m.ReplicaOf
	}
	return nil
}

func init() {
	proto.RegisterEnum("akash.deployment.v1.VolumePolicy_ReclaimPolicy", VolumePolicy_ReclaimPolicy_name, VolumePolicy_ReclaimPolicy_value)
	proto.RegisterType((*VolumeRef)(nil), "akash.deployment.v1.VolumeRef")
	proto.RegisterType((*VolumePolicy)(nil), "akash.deployment.v1.VolumePolicy")
}

func init() { proto.RegisterFile("akash/deployment/v1/volume.proto", fileDescriptor_0bf9664fe5f0b80a) }

var fileDescriptor_0bf9664fe5f0b80a = []byte{
	// 691 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4f, 0x4f, 0xdb, 0x48,
	0x14, 0x8f, 0x21, 0x84, 0x65, 0xf8, 0xb3, 0x91, 0xc9, 0x2e, 0x21, 0xab, 0xf5, 0xa4, 0x53, 0x55,
	0x50, 0xb5, 0xd8, 0x0a, 0xdc, 0xe0, 0x44, 0x84, 0x84, 0xda, 0x4b, 0xab, 0x41, 0xe2, 0xd0, 0x0b,
	0x1a, 0xe2, 0x89, 0xb1, 0xb0, 0x3d, 0xc1, 0x36, 0x2e, 0xe9, 0x07, 0xa8, 0x2a, 0x4e, 0x3d, 0x72,
	0x41, 0x42, 0xea, 0x57, 0xe8, 0x87, 0xe0, 0x88, 0x7a, 0xea, 0x69, 0x5a, 0x85, 0x4b, 0xe5, 0xa3,
	0xa5, 0xde, 0xab, 0x99, 0xb1, 0xe5, 0x86, 0xa2, 0xaa, 0xa7, 0xe4, 0xfd, 0xfe, 0xbd, 0x37, 0xf3,
	0x26, 0x01, 0x6d, 0x72, 0x4c, 0xa2, 0x23, 0xcb, 0xa6, 0x03, 0x8f, 0x0d, 0x7d, 0x1a, 0xc4, 0x56,
	0xd2, 0xb1, 0x12, 0xe6, 0x9d, 0xfa, 0xd4, 0x1c, 0x84, 0x2c, 0x66, 0xfa, 0xa2, 0x54, 0x98, 0xa5,
	0xc2, 0x4c, 0x3a, 0xad, 0x86, 0xc3, 0x1c, 0x26, 0x79, 0x4b, 0x7c, 0x53, 0xd2, 0xd6, 0x72, 0x8f,
	0x45, 0x3e, 0x8b, 0x0e, 0x14, 0xa1, 0x8a, 0x9c, 0x32, 0x1c, 0xc6, 0x1c, 0x8f, 0x5a, 0xb2, 0x3a,
	0x3c, 0xed, 0x5b, 0xf6, 0x69, 0x48, 0x62, 0x97, 0x05, 0x8a, 0x47, 0xdf, 0x35, 0x30, 0xb3, 0x2f,
	0xdb, 0x62, 0xda, 0xd7, 0x77, 0xc1, 0x14, 0x7b, 0x1d, 0xd0, 0xb0, 0xa9, 0xb5, 0xb5, 0xd5, 0x99,
	0x6e, 0x27, 0xe5, 0x50, 0x01, 0x19, 0x87, 0x73, 0x43, 0xe2, 0x7b, 0x9b, 0x48, 0x96, 0xe8, 0xd3,
	0xc7, 0xb5, 0x46, 0xde, 0x67, 0xdb, 0xb6, 0x43, 0x1a, 0x45, 0x7b, 0x71, 0xe8, 0x06, 0x0e, 0x56,
	0x72, 0x7d, 0x03, 0x54, 0xed, 0x88, 0x9e, 0x34, 0x27, 0xda, 0xda, 0x6a, 0xb5, 0x0b, 0x47, 0x1c,
	0x56, 0x77, 0xf6, 0xe8, 0x49, 0xca, 0xa1, 0xc4, 0x33, 0x0e, 0x67, 0x55, 0x9c, 0xa8, 0x10, 0x96,
	0xa0, 0x30, 0x39, 0xc2, 0x34, 0xd9, 0xd6, 0x56, 0xe7, 0x95, 0x69, 0x37, 0x37, 0x39, 0x63, 0x26,
	0x47, 0x99, 0xc4, 0x87, 0xfe, 0x04, 0x54, 0x03, 0xe2, 0xd3, 0x66, 0x55, 0x4e, 0xbc, 0x24, 0xc4,
	0xa2, 0x2e, 0xc5, 0xa2, 0x42, 0x58, 0x82, 0x9b, 0x7f, 0x5d, 0x5c, 0xc1, 0xca, 0xb7, 0x2b, 0xa8,
	0xa1, 0xcb, 0x1a, 0x98, 0x53, 0xe7, 0x7e, 0xc9, 0x3c, 0xb7, 0x37, 0xd4, 0x57, 0xc0, 0x64, 0xe2,
	0xda, 0xf9, 0xc1, 0xff, 0x49, 0x39, 0x14, 0x65, 0xc6, 0x21, 0x50, 0x29, 0x89, 0x6b, 0x23, 0x2c,
	0x20, 0xfd, 0x08, 0x4c, 0x87, 0xb4, 0xe7, 0x11, 0xd7, 0x97, 0xa7, 0x5b, 0x58, 0xb7, 0xcc, 0x7b,
	0x36, 0x65, 0xfe, 0x1c, 0x6e, 0x62, 0x65, 0x50, 0x55, 0xf7, 0xff, 0x94, 0xc3, 0x22, 0x23, 0xe3,
	0x70, 0x41, 0x75, 0xc8, 0x01, 0x84, 0x0b, 0x4a, 0x3f, 0x04, 0x33, 0x21, 0x8d, 0x69, 0x20, 0xd6,
	0x25, 0x2f, 0x65, 0x76, 0x7d, 0xd9, 0x54, 0xfb, 0x34, 0x8b, 0x7d, 0x9a, 0x3b, 0xf9, 0x3e, 0xbb,
	0x8f, 0xaf, 0x39, 0xac, 0xa4, 0x1c, 0x96, 0x9e, 0x8c, 0xc3, 0x7a, 0x91, 0x9d, 0x43, 0xe8, 0xe2,
	0x0b, 0xd4, 0x70, 0x29, 0xd1, 0xf7, 0xc1, 0xdf, 0x3e, 0x39, 0x3b, 0x20, 0x71, 0x4c, 0x7a, 0x47,
	0x62, 0xf6, 0x48, 0xde, 0xe4, 0x7c, 0x77, 0x2d, 0xe5, 0xf0, 0x2e, 0x95, 0x71, 0xf8, 0xaf, 0x0a,
	0xbc, 0x43, 0x20, 0xbc, 0xe0, 0x93, 0xb3, 0xed, 0x12, 0xd0, 0x9f, 0x83, 0x39, 0xa1, 0x09, 0xe9,
	0xc0, 0x73, 0x7b, 0x24, 0x6a, 0x4e, 0xc9, 0xd0, 0x95, 0x94, 0xc3, 0x31, 0x3c, 0xe3, 0x70, 0xb1,
	0x4c, 0x2c, 0x50, 0x84, 0x67, 0x7d, 0x72, 0x86, 0xf3, 0x4a, 0x77, 0xc0, 0x14, 0xb1, 0xd9, 0x20,
	0x6e, 0xd6, 0xe4, 0x1d, 0x18, 0xbf, 0xb9, 0x6f, 0x4c, 0xfb, 0xdd, 0xce, 0x35, 0x87, 0x9a, 0x98,
	0x5e, 0x9a, 0x9e, 0x32, 0xdf, 0x8d, 0xa9, 0x3f, 0x88, 0x87, 0xe5, 0xf4, 0x77, 0x08, 0x84, 0x55,
	0xbe, 0xfe, 0x06, 0x80, 0x7c, 0x84, 0x03, 0xd6, 0x6f, 0x4e, 0xff, 0x51, 0xb7, 0xad, 0xbc, 0x5b,
	0xa3, 0x74, 0x8e, 0xb5, 0xfc, 0xaf, 0xd8, 0xc0, 0xaf, 0x2c, 0x12, 0x8b, 0x90, 0xf0, 0x8b, 0x3e,
	0x7a, 0xab, 0x81, 0xf9, 0xb1, 0x67, 0xa2, 0x3f, 0x02, 0xd3, 0x6e, 0x90, 0x10, 0xcf, 0xb5, 0xeb,
	0x95, 0x56, 0xf3, 0xfc, 0xb2, 0xdd, 0x28, 0xba, 0x4a, 0xd5, 0x33, 0xc5, 0xe9, 0x0f, 0x41, 0x2d,
	0xa4, 0x31, 0x71, 0x83, 0xba, 0xd6, 0x5a, 0x3a, 0xbf, 0x6c, 0x2f, 0x8e, 0xa9, 0xb0, 0xa4, 0x84,
	0xc8, 0xa6, 0x1e, 0x8d, 0x69, 0x7d, 0xe2, 0x1e, 0xd1, 0x8e, 0xa4, 0x5a, 0xd5, 0x77, 0x1f, 0x8c,
	0xca, 0x66, 0x55, 0xfc, 0x3e, 0xba, 0x5b, 0xd7, 0x23, 0x43, 0xbb, 0x19, 0x19, 0xda, 0xd7, 0x91,
	0xa1, 0xbd, 0xbf, 0x35, 0x2a, 0x37, 0xb7, 0x46, 0xe5, 0xf3, 0xad, 0x51, 0x79, 0xf5, 0x60, 0x70,
	0xec, 0x98, 0xe4, 0x38, 0x36, 0x6d, 0x9a, 0x58, 0x0e, 0xb3, 0x02, 0x66, 0xd3, 0xf1, 0xff, 0xb1,
	0xc3, 0x9a, 0x7c, 0x9d, 0x1b, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x3c, 0x69, 0x7f, 0xe5,
	0x04, 0x00, 0x00,
}

func (this *VolumeRef) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VolumeRef)
	if !ok {
		that2, ok := that.(VolumeRef)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Owner != that1.Owner {
		return false
	}
	if this.DSeq != that1.DSeq {
		return false
	}
	if this.GSeq != that1.GSeq {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	return true
}
func (this *VolumePolicy) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VolumePolicy)
	if !ok {
		that2, ok := that.(VolumePolicy)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Vid != that1.Vid {
		return false
	}
	if this.Reclaim != that1.Reclaim {
		return false
	}
	if this.Retention != that1.Retention {
		return false
	}
	if this.MaxAttachments != that1.MaxAttachments {
		return false
	}
	if this.MaxReplicas != that1.MaxReplicas {
		return false
	}
	if !this.Adopt.Equal(that1.Adopt) {
		return false
	}
	if !this.ReplicaOf.Equal(that1.ReplicaOf) {
		return false
	}
	return true
}
func (m *VolumeRef) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VolumeRef) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VolumeRef) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintVolume(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x22
	}
	if m.GSeq != 0 {
		i = encodeVarintVolume(dAtA, i, uint64(m.GSeq))
		i--
		dAtA[i] = 0x18
	}
	if m.DSeq != 0 {
		i = encodeVarintVolume(dAtA, i, uint64(m.DSeq))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintVolume(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VolumePolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VolumePolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VolumePolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReplicaOf != nil {
		{
			size, err := m.ReplicaOf.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintVolume(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.Adopt != nil {
		{
			size, err := m.Adopt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintVolume(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.MaxReplicas != 0 {
		i = encodeVarintVolume(dAtA, i, uint64(m.MaxReplicas))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxAttachments != 0 {
		i = encodeVarintVolume(dAtA, i, uint64(m.MaxAttachments))
		i--
		dAtA[i] = 0x20
	}
	n3, err3 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.Retention, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Retention):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintVolume(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x1a
	if m.Reclaim != 0 {
		i = encodeVarintVolume(dAtA, i, uint64(m.Reclaim))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Vid) > 0 {
		i -= len(m.Vid)
		copy(dAtA[i:], m.Vid)
		i = encodeVarintVolume(dAtA, i, uint64(len(m.Vid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVolume(dAtA []byte, offset int, v uint64) int {
	offset -= sovVolume(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VolumeRef) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovVolume(uint64(l))
	}
	if m.DSeq != 0 {
		n += 1 + sovVolume(uint64(m.DSeq))
	}
	if m.GSeq != 0 {
		n += 1 + sovVolume(uint64(m.GSeq))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovVolume(uint64(l))
	}
	return n
}

func (m *VolumePolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Vid)
	if l > 0 {
		n += 1 + l + sovVolume(uint64(l))
	}
	if m.Reclaim != 0 {
		n += 1 + sovVolume(uint64(m.Reclaim))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Retention)
	n += 1 + l + sovVolume(uint64(l))
	if m.MaxAttachments != 0 {
		n += 1 + sovVolume(uint64(m.MaxAttachments))
	}
	if m.MaxReplicas != 0 {
		n += 1 + sovVolume(uint64(m.MaxReplicas))
	}
	if m.Adopt != nil {
		l = m.Adopt.Size()
		n += 1 + l + sovVolume(uint64(l))
	}
	if m.ReplicaOf != nil {
		l = m.ReplicaOf.Size()
		n += 1 + l + sovVolume(uint64(l))
	}
	return n
}

func sovVolume(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVolume(x uint64) (n int) {
	return sovVolume(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VolumeRef) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVolume
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VolumeRef: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VolumeRef: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolume
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVolume
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVolume
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DSeq", wireType)
			}
			m.DSeq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolume
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DSeq |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GSeq", wireType)
			}
			m.GSeq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolume
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GSeq |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolume
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVolume
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVolume
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVolume(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVolume
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VolumePolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVolume
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VolumePolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VolumePolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolume
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVolume
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVolume
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reclaim", wireType)
			}
			m.Reclaim = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolume
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reclaim |= VolumePolicy_ReclaimPolicy(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Retention", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolume
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVolume
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVolume
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.Retention, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAttachments", wireType)
			}
			m.MaxAttachments = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolume
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxAttachments |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxReplicas", wireType)
			}
			m.MaxReplicas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolume
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxReplicas |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Adopt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolume
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVolume
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVolume
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Adopt == nil {
				m.Adopt = &VolumeRef{}
			}
			if err := m.Adopt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplicaOf", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVolume
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVolume
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVolume
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ReplicaOf == nil {
				m.ReplicaOf = &VolumeRef{}
			}
			if err := m.ReplicaOf.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVolume(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVolume
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVolume(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVolume
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVolume
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVolume
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVolume
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVolume
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVolume
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVolume        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVolume          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVolume = fmt.Errorf("proto: unexpected end of group")
)
