// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/escrow/v1/event.proto

package v1

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	v1 "pkg.akt.dev/go/node/escrow/id/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventAccountRunway is emitted at every settle of an account with open
// payments: the deterministic, tenant-computable exhaustion deadline.
type EventAccountRunway struct {
	// ID is the unique identifier of the account.
	ID v1.Account `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	// ProjectedDepletionHeight is the block height at which the account's
	// funds no longer cover its open payment rates. 0 means the funds cover
	// no full block.
	ProjectedDepletionHeight int64 `protobuf:"varint,2,opt,name=projected_depletion_height,json=projectedDepletionHeight,proto3" json:"projected_depletion_height" yaml:"projected_depletion_height"`
}

func (m *EventAccountRunway) Reset()         { *m = EventAccountRunway{} }
func (m *EventAccountRunway) String() string { return proto.CompactTextString(m) }
func (*EventAccountRunway) ProtoMessage()    {}
func (*EventAccountRunway) Descriptor() ([]byte, []int) {
	return fileDescriptor_5463a52468085b24, []int{0}
}
func (m *EventAccountRunway) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventAccountRunway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventAccountRunway.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventAccountRunway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAccountRunway.Merge(m, src)
}
func (m *EventAccountRunway) XXX_Size() int {
	return m.Size()
}
func (m *EventAccountRunway) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAccountRunway.DiscardUnknown(m)
}

var xxx_messageInfo_EventAccountRunway proto.InternalMessageInfo

func (m *EventAccountRunway) GetID() v1.Account {
	if m != nil {
		return m.ID
	}
	return v1.Account{}
}

func (m *EventAccountRunway) GetProjectedDepletionHeight() int64 {
	if m != nil {
		return m.ProjectedDepletionHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*EventAccountRunway)(nil), "akash.escrow.v1.EventAccountRunway")
}

func init() { proto.RegisterFile("akash/escrow/v1/event.proto", fileDescriptor_5463a52468085b24) }

var fileDescriptor_5463a52468085b24 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0xcc, 0x4e, 0x2c,
	0xce, 0xd0, 0x4f, 0x2d, 0x4e, 0x2e, 0xca, 0x2f, 0xd7, 0x2f, 0x33, 0xd4, 0x4f, 0x2d, 0x4b, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x07, 0x4b, 0xea, 0x41, 0x24, 0xf5, 0xca,
	0x0c, 0xa5, 0x44, 0xd2, 0xf3, 0xd3, 0xf3, 0xc1, 0x72, 0xfa, 0x20, 0x16, 0x44, 0x99, 0x14, 0xaa,
	0x19, 0x99, 0x29, 0x20, 0x63, 0x32, 0x53, 0x20, 0x92, 0x4a, 0x4f, 0x18, 0xb9, 0x84, 0x5c, 0x41,
	0x66, 0x3a, 0x26, 0x27, 0xe7, 0x97, 0xe6, 0x95, 0x04, 0x95, 0xe6, 0x95, 0x27, 0x56, 0x0a, 0x79,
	0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x49, 0xeb, 0xa1, 0xd8, 0x93,
	0x99, 0xa2, 0x57, 0x66, 0xa8, 0x07, 0x55, 0xee, 0x24, 0x7b, 0xe2, 0x9e, 0x3c, 0xc3, 0xa3, 0x7b,
	0xf2, 0x4c, 0x9e, 0x2e, 0xaf, 0xee, 0xc9, 0x33, 0x65, 0xa6, 0x7c, 0xba, 0x27, 0xcf, 0x59, 0x99,
	0x98, 0x9b, 0x63, 0xa5, 0x94, 0x99, 0xa2, 0x14, 0xc4, 0x94, 0x99, 0x22, 0xd4, 0xc8, 0xc8, 0x25,
	0x55, 0x50, 0x94, 0x9f, 0x95, 0x9a, 0x5c, 0x92, 0x9a, 0x12, 0x9f, 0x92, 0x5a, 0x90, 0x93, 0x5a,
	0x92, 0x99, 0x9f, 0x17, 0x9f, 0x91, 0x9a, 0x99, 0x9e, 0x51, 0x22, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1,
	0xec, 0xe4, 0xfc, 0xea, 0x9e, 0x3c, 0x1e, 0x55, 0x9f, 0xee, 0xc9, 0x2b, 0x42, 0x4c, 0xc5, 0xad,
	0x46, 0x29, 0x48, 0x02, 0x2e, 0xe9, 0x02, 0x93, 0xf3, 0x00, 0x4b, 0x39, 0x99, 0x9f, 0x78, 0x24,
	0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13, 0x1e, 0xcb, 0x31, 0x5c, 0x78,
	0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43, 0x94, 0x6c, 0x41, 0x76, 0xba, 0x5e, 0x62, 0x76, 0x89,
	0x5e, 0x4a, 0x6a, 0x99, 0x7e, 0x7a, 0xbe, 0x7e, 0x5e, 0x7e, 0x4a, 0x2a, 0x22, 0xbc, 0x93, 0xd8,
	0xc0, 0xc1, 0x64, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x6e, 0x04, 0xdd, 0x89, 0x01, 0x00,
	0x00,
}

func (m *EventAccountRunway) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventAccountRunway) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventAccountRunway) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProjectedDepletionHeight != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.ProjectedDepletionHeight))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventAccountRunway) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEvent(uint64(l))
	if m.ProjectedDepletionHeight != 0 {
		n += 1 + sovEvent(uint64(m.ProjectedDepletionHeight))
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventAccountRunway) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventAccountRunway: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventAccountRunway: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectedDepletionHeight", wireType)
			}
			m.ProjectedDepletionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProjectedDepletionHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
