// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/deployment/v1beta5/deploymentmsg.proto

package v1beta5

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	v1 "pkg.akt.dev/go/node/deployment/v1"
	v11 "pkg.akt.dev/go/node/types/deposit/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgCreateDeployment defines an SDK message for creating deployment.
type MsgCreateDeployment struct {
	// ID is the unique identifier of the deployment.
	ID v1.DeploymentID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	// GroupSpec is a list of group specifications for the deployment.
	// This field is required and must be a list of GroupSpec.
	Groups GroupSpecs `protobuf:"bytes,2,rep,name=groups,proto3,castrepeated=GroupSpecs" json:"groups" yaml:"groups"`
	// Hash of the deployment.
	Hash []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash" yaml:"hash"`
	// Deposit specifies the amount of coins to include in the deployment's first deposit.
	Deposit v11.Deposit `protobuf:"bytes,4,opt,name=deposit,proto3" json:"deposit" yaml:"deposit"`
	// reclamation specifies the deployment-level reclamation requirements.
	// Nil means the tenant does not require reclamation.
	Reclamation *v1.DeploymentReclamation `protobuf:"bytes,5,opt,name=reclamation,proto3" json:"reclamation,omitempty" yaml:"reclamation,omitempty"`
}

func (m *MsgCreateDeployment) Reset()         { *m = MsgCreateDeployment{} }
func (m *MsgCreateDeployment) String() string { return proto.CompactTextString(m) }
func (*MsgCreateDeployment) ProtoMessage()    {}
func (*MsgCreateDeployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6dd2ebde242e117, []int{0}
}
func (m *MsgCreateDeployment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateDeployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateDeployment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateDeployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateDeployment.Merge(m, src)
}
func (m *MsgCreateDeployment) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateDeployment) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateDeployment.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateDeployment proto.InternalMessageInfo

func (m *MsgCreateDeployment) GetID() v1.DeploymentID {
	if m != nil {
		return m.ID
	}
	return v1.DeploymentID{}
}

func (m *MsgCreateDeployment) GetGroups() GroupSpecs {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *MsgCreateDeployment) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *MsgCreateDeployment) GetDeposit() v11.Deposit {
	if m != nil {
		return m.Deposit
	}
	return v11.Deposit{}
}

func (m *MsgCreateDeployment) GetReclamation() *v1.DeploymentReclamation {
	if m != nil {
		return m.Reclamation
	}
	return nil
}

// MsgCreateDeploymentResponse defines the Msg/CreateDeployment response type.
type MsgCreateDeploymentResponse struct {
}

func (m *MsgCreateDeploymentResponse) Reset()         { *m = MsgCreateDeploymentResponse{} }
func (m *MsgCreateDeploymentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateDeploymentResponse) ProtoMessage()    {}
func (*MsgCreateDeploymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6dd2ebde242e117, []int{1}
}
func (m *MsgCreateDeploymentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateDeploymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateDeploymentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateDeploymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateDeploymentResponse.Merge(m, src)
}
func (m *MsgCreateDeploymentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateDeploymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateDeploymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateDeploymentResponse proto.InternalMessageInfo

// MsgUpdateDeployment defines an SDK message for updating deployment.
type MsgUpdateDeployment struct {
	// ID is the unique identifier of the deployment.
	ID v1.DeploymentID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
	// Hash of the deployment.
	Hash []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash" yaml:"hash"`
}

func (m *MsgUpdateDeployment) Reset()         { *m = MsgUpdateDeployment{} }
func (m *MsgUpdateDeployment) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateDeployment) ProtoMessage()    {}
func (*MsgUpdateDeployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6dd2ebde242e117, []int{2}
}
func (m *MsgUpdateDeployment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateDeployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateDeployment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateDeployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateDeployment.Merge(m, src)
}
func (m *MsgUpdateDeployment) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateDeployment) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateDeployment.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateDeployment proto.InternalMessageInfo

func (m *MsgUpdateDeployment) GetID() v1.DeploymentID {
	if m != nil {
		return m.ID
	}
	return v1.DeploymentID{}
}

func (m *MsgUpdateDeployment) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

// MsgUpdateDeploymentResponse defines the Msg/UpdateDeployment response type.
type MsgUpdateDeploymentResponse struct {
}

func (m *MsgUpdateDeploymentResponse) Reset()         { *m = MsgUpdateDeploymentResponse{} }
func (m *MsgUpdateDeploymentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateDeploymentResponse) ProtoMessage()    {}
func (*MsgUpdateDeploymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6dd2ebde242e117, []int{3}
}
func (m *MsgUpdateDeploymentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateDeploymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateDeploymentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateDeploymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateDeploymentResponse.Merge(m, src)
}
func (m *MsgUpdateDeploymentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateDeploymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateDeploymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateDeploymentResponse proto.InternalMessageInfo

// MsgCloseDeployment defines an SDK message for closing deployment
type MsgCloseDeployment struct {
	// ID is the unique identifier of the deployment.
	ID v1.DeploymentID `protobuf:"bytes,1,opt,name=id,proto3" json:"id" yaml:"id"`
}

func (m *MsgCloseDeployment) Reset()         { *m = MsgCloseDeployment{} }
func (m *MsgCloseDeployment) String() string { return proto.CompactTextString(m) }
func (*MsgCloseDeployment) ProtoMessage()    {}
func (*MsgCloseDeployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6dd2ebde242e117, []int{4}
}
func (m *MsgCloseDeployment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCloseDeployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCloseDeployment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCloseDeployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCloseDeployment.Merge(m, src)
}
func (m *MsgCloseDeployment) XXX_Size() int {
	return m.Size()
}
func (m *MsgCloseDeployment) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCloseDeployment.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCloseDeployment proto.InternalMessageInfo

func (m *MsgCloseDeployment) GetID() v1.DeploymentID {
	if m != nil {
		return m.ID
	}
	return v1.DeploymentID{}
}

// MsgCloseDeploymentResponse defines the Msg/CloseDeployment response type.
type MsgCloseDeploymentResponse struct {
}

func (m *MsgCloseDeploymentResponse) Reset()         { *m = MsgCloseDeploymentResponse{} }
func (m *MsgCloseDeploymentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCloseDeploymentResponse) ProtoMessage()    {}
func (*MsgCloseDeploymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6dd2ebde242e117, []int{5}
}
func (m *MsgCloseDeploymentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCloseDeploymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCloseDeploymentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCloseDeploymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCloseDeploymentResponse.Merge(m, src)
}
func (m *MsgCloseDeploymentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCloseDeploymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCloseDeploymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCloseDeploymentResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateDeployment)(nil), "akash.deployment.v1beta5.MsgCreateDeployment")
	proto.RegisterType((*MsgCreateDeploymentResponse)(nil), "akash.deployment.v1beta5.MsgCreateDeploymentResponse")
	proto.RegisterType((*MsgUpdateDeployment)(nil), "akash.deployment.v1beta5.MsgUpdateDeployment")
	proto.RegisterType((*MsgUpdateDeploymentResponse)(nil), "akash.deployment.v1beta5.MsgUpdateDeploymentResponse")
	proto.RegisterType((*MsgCloseDeployment)(nil), "akash.deployment.v1beta5.MsgCloseDeployment")
	proto.RegisterType((*MsgCloseDeploymentResponse)(nil), "akash.deployment.v1beta5.MsgCloseDeploymentResponse")
}

func init() {
	proto.RegisterFile("akash/deployment/v1beta5/deploymentmsg.proto", fileDescriptor_f6dd2ebde242e117)
}

var fileDescriptor_f6dd2ebde242e117 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x31, 0x8f, 0xd3, 0x30,
	0x14, 0xc7, 0x93, 0xb4, 0x1c, 0xc2, 0x05, 0x86, 0x00, 0x22, 0x2a, 0x77, 0x71, 0x2f, 0x87, 0x50,
	0x05, 0x87, 0x23, 0x0e, 0xb1, 0x9c, 0x84, 0x84, 0x42, 0x25, 0x74, 0x03, 0x12, 0x0a, 0x62, 0x81,
	0xc9, 0x6d, 0xac, 0x34, 0x34, 0xa9, 0xad, 0x3a, 0x9c, 0xd4, 0xcf, 0xc0, 0xc2, 0xcc, 0xc4, 0xcc,
	0x27, 0xe9, 0x78, 0x23, 0x93, 0x41, 0xed, 0x82, 0xba, 0x91, 0x4f, 0x80, 0x1c, 0x3b, 0x6d, 0x81,
	0x9c, 0xd0, 0x0d, 0xdd, 0xfc, 0xec, 0xdf, 0xfb, 0xbf, 0xff, 0x7b, 0xb6, 0xc1, 0x21, 0x1e, 0x61,
	0x3e, 0xf4, 0x23, 0xc2, 0x52, 0x3a, 0xcd, 0xc8, 0x38, 0xf7, 0x4f, 0x1f, 0xf5, 0x49, 0x8e, 0x9f,
	0x6c, 0x6c, 0x65, 0x3c, 0x46, 0x6c, 0x42, 0x73, 0x6a, 0x3b, 0x25, 0x8d, 0xd6, 0x47, 0x48, 0xd3,
	0xed, 0x9b, 0x31, 0x8d, 0x69, 0x09, 0xf9, 0x72, 0xa5, 0xf8, 0xf6, 0xdd, 0x1a, 0xf5, 0x8d, 0x48,
	0x53, 0xdd, 0x73, 0x3d, 0xc4, 0x13, 0xfa, 0x81, 0x71, 0x46, 0x06, 0x9a, 0x3c, 0x50, 0x64, 0x1f,
	0x73, 0x22, 0x71, 0xca, 0x93, 0x4a, 0x51, 0x2e, 0x15, 0xe4, 0xfd, 0x6a, 0x80, 0x1b, 0x2f, 0x79,
	0xfc, 0x7c, 0x42, 0x70, 0x4e, 0x7a, 0x2b, 0x51, 0xfb, 0x15, 0xb0, 0x92, 0xc8, 0x31, 0x3b, 0x66,
	0xb7, 0x75, 0xb4, 0x8f, 0x6a, 0x3a, 0x41, 0x6b, 0xf8, 0xa4, 0x17, 0xec, 0xcd, 0x04, 0x34, 0xe6,
	0x02, 0x5a, 0x27, 0xbd, 0xa5, 0x80, 0x56, 0x12, 0x15, 0x02, 0x5e, 0x99, 0xe2, 0x2c, 0x3d, 0xf6,
	0x92, 0xc8, 0x0b, 0xad, 0x24, 0xb2, 0xdf, 0x83, 0x1d, 0xe5, 0xd0, 0xb1, 0x3a, 0x8d, 0x6e, 0xeb,
	0xe8, 0x00, 0x9d, 0x37, 0x1f, 0xf4, 0x42, 0x72, 0xaf, 0x19, 0x19, 0x04, 0x0f, 0xa5, 0xee, 0x52,
	0x40, 0x9d, 0x5a, 0x08, 0x78, 0x4d, 0xa9, 0xaa, 0xd8, 0xfb, 0xfa, 0x1d, 0x82, 0x15, 0xcd, 0x43,
	0x8d, 0xd9, 0x0f, 0x40, 0x73, 0x88, 0xf9, 0xd0, 0x69, 0x74, 0xcc, 0xee, 0xd5, 0xe0, 0xf6, 0x52,
	0xc0, 0x32, 0x2e, 0x04, 0x6c, 0xa9, 0x74, 0x19, 0x79, 0x61, 0xb9, 0x69, 0xbf, 0x03, 0x97, 0xf5,
	0x4c, 0x9c, 0x66, 0xd9, 0xaf, 0xab, 0x9d, 0xc9, 0xc9, 0xa1, 0x6a, 0x5c, 0xaa, 0x63, 0xb9, 0x0c,
	0xf6, 0xb5, 0xa9, 0x2a, 0xad, 0x10, 0xf0, 0xba, 0x92, 0xd5, 0x1b, 0x5e, 0x58, 0x1d, 0xd9, 0x1f,
	0x4d, 0xd0, 0x9a, 0x90, 0x41, 0x8a, 0x33, 0x9c, 0x27, 0x74, 0xec, 0x5c, 0x2a, 0x2b, 0xdc, 0xff,
	0xcf, 0x44, 0xc3, 0x75, 0x46, 0xf0, 0x74, 0x26, 0xa0, 0xb9, 0x14, 0xf0, 0xd6, 0x86, 0xcc, 0x21,
	0xcd, 0x92, 0x9c, 0x64, 0x2c, 0x9f, 0x16, 0x02, 0xee, 0xaa, 0xda, 0xb5, 0xc7, 0x5e, 0xb8, 0x59,
	0xfd, 0xb8, 0xf9, 0xf3, 0x0b, 0x34, 0xbc, 0x3d, 0x70, 0xa7, 0xe6, 0xca, 0x43, 0xc2, 0x19, 0x1d,
	0x73, 0xe2, 0x7d, 0x36, 0xcb, 0x27, 0xf1, 0x86, 0x45, 0xdb, 0x7e, 0x12, 0x17, 0xb9, 0xa6, 0x3f,
	0xbc, 0xff, 0xed, 0x6d, 0xe5, 0x3d, 0x05, 0xb6, 0x6c, 0x2d, 0xa5, 0x7c, 0xab, 0xce, 0xb5, 0x99,
	0x5d, 0xd0, 0xfe, 0xb7, 0x5a, 0xe5, 0x25, 0x78, 0x36, 0x9b, 0xbb, 0xe6, 0xd9, 0xdc, 0x35, 0x7f,
	0xcc, 0x5d, 0xf3, 0xd3, 0xc2, 0x35, 0xce, 0x16, 0xae, 0xf1, 0x6d, 0xe1, 0x1a, 0x6f, 0xef, 0xb1,
	0x51, 0x8c, 0xf0, 0x28, 0x47, 0x11, 0x39, 0xf5, 0x63, 0xea, 0x8f, 0x69, 0x44, 0x6a, 0x7e, 0x74,
	0x7f, 0xa7, 0xfc, 0xa3, 0x8f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x89, 0xa1, 0xe0, 0x20, 0x78,
	0x04, 0x00, 0x00,
}

func (m *MsgCreateDeployment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateDeployment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateDeployment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reclamation != nil {
		{
			size, err := m.Reclamation.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDeploymentmsg(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	{
		size, err := m.Deposit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintDeploymentmsg(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintDeploymentmsg(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Groups) > 0 {
		for iNdEx := len(m.Groups) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Groups[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDeploymentmsg(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintDeploymentmsg(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgCreateDeploymentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateDeploymentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateDeploymentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateDeployment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateDeployment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateDeployment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintDeploymentmsg(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintDeploymentmsg(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgUpdateDeploymentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateDeploymentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateDeploymentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCloseDeployment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCloseDeployment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCloseDeployment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintDeploymentmsg(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgCloseDeploymentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCloseDeploymentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCloseDeploymentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintDeploymentmsg(dAtA []byte, offset int, v uint64) int {
	offset -= sovDeploymentmsg(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateDeployment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovDeploymentmsg(uint64(l))
	if len(m.Groups) > 0 {
		for _, e := range m.Groups {
			l = e.Size()
			n += 1 + l + sovDeploymentmsg(uint64(l))
		}
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovDeploymentmsg(uint64(l))
	}
	l = m.Deposit.Size()
	n += 1 + l + sovDeploymentmsg(uint64(l))
	if m.Reclamation != nil {
		l = m.Reclamation.Size()
		n += 1 + l + sovDeploymentmsg(uint64(l))
	}
	return n
}

func (m *MsgCreateDeploymentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateDeployment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovDeploymentmsg(uint64(l))
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovDeploymentmsg(uint64(l))
	}
	return n
}

func (m *MsgUpdateDeploymentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCloseDeployment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovDeploymentmsg(uint64(l))
	return n
}

func (m *MsgCloseDeploymentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovDeploymentmsg(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDeploymentmsg(x uint64) (n int) {
	return sovDeploymentmsg(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateDeployment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeploymentmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateDeployment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateDeployment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeploymentmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Groups", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeploymentmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Groups = append(m.Groups, GroupSpec{})
			if err := m.Groups[len(m.Groups)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeploymentmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeploymentmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Deposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reclamation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeploymentmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Reclamation == nil {
				m.Reclamation = &v1.DeploymentReclamation{}
			}
			if err := m.Reclamation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDeploymentmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateDeploymentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeploymentmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateDeploymentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateDeploymentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDeploymentmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateDeployment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeploymentmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateDeployment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateDeployment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeploymentmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeploymentmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDeploymentmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateDeploymentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeploymentmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateDeploymentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateDeploymentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDeploymentmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCloseDeployment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeploymentmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCloseDeployment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCloseDeployment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeploymentmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDeploymentmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCloseDeploymentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeploymentmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCloseDeploymentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCloseDeploymentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipDeploymentmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeploymentmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDeploymentmsg(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDeploymentmsg
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDeploymentmsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDeploymentmsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDeploymentmsg
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDeploymentmsg
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDeploymentmsg
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDeploymentmsg        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDeploymentmsg          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDeploymentmsg = fmt.Errorf("proto: unexpected end of group")
)
