// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/deployment/v1beta5/groupspec.proto

package v1beta5

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	v11 "pkg.akt.dev/go/node/deployment/v1"
	v1 "pkg.akt.dev/go/node/types/attributes/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GroupSpec defines a specification for a group in a deployment on the network.
// This includes attributes like the group name, placement requirements, and resource units.
type GroupSpec struct {
	// Name is the name of the group.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" yaml:"name"`
	// Requirements specifies the placement requirements for the group.
	// This determines where the resources in the group can be deployed.
	Requirements v1.PlacementRequirements `protobuf:"bytes,2,opt,name=requirements,proto3" json:"requirements" yaml:"requirements"`
	// Resources is a list containing the resource units allocated to the group.
	// Each ResourceUnit defines the specific resources (e.g., CPU, memory) assigned.
	Resources ResourceUnits `protobuf:"bytes,3,rep,name=resources,proto3,castrepeated=ResourceUnits" json:"resources" yaml:"resources"`
	// Volume, when set, declares this a storage-only volume group and carries
	// its lifecycle contract. Nil for every pre-AEP-87 group, so the store
	// migration is re-serialization only.
	Volume *v11.VolumePolicy `protobuf:"bytes,4,opt,name=volume,proto3" json:"volume,omitempty" yaml:"volume,omitempty"`
}

func (m *GroupSpec) Reset()         { *m = GroupSpec{} }
func (m *GroupSpec) String() string { return proto.CompactTextString(m) }
func (*GroupSpec) ProtoMessage()    {}
func (*GroupSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_d659f0a7bce863e5, []int{0}
}
func (m *GroupSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GroupSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GroupSpec.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GroupSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupSpec.Merge(m, src)
}
func (m *GroupSpec) XXX_Size() int {
	return m.Size()
}
func (m *GroupSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupSpec.DiscardUnknown(m)
}

var xxx_messageInfo_GroupSpec proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GroupSpec)(nil), "akash.deployment.v1beta5.GroupSpec")
}

func init() {
	proto.RegisterFile("akash/deployment/v1beta5/groupspec.proto", fileDescriptor_d659f0a7bce863e5)
}

var fileDescriptor_d659f0a7bce863e5 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x31, 0x8f, 0xd3, 0x30,
	0x14, 0xc7, 0x63, 0x7a, 0x3a, 0xd1, 0x14, 0xa4, 0x53, 0x40, 0xba, 0xe8, 0x86, 0x38, 0x64, 0x38,
	0x45, 0x2a, 0xb2, 0xd5, 0x3b, 0xc1, 0x70, 0x13, 0xca, 0xc2, 0x7a, 0x0a, 0x82, 0x81, 0xcd, 0x49,
	0xad, 0x10, 0x35, 0x89, 0x43, 0xec, 0x44, 0x8a, 0xc4, 0xc0, 0xc8, 0xc8, 0x47, 0xb8, 0x99, 0x95,
	0x2f, 0xd1, 0xb1, 0x23, 0x93, 0x41, 0xed, 0x82, 0x3a, 0xe6, 0x13, 0xa0, 0x38, 0xa9, 0xd2, 0xa2,
	0x76, 0xf3, 0x7b, 0xfe, 0xbd, 0xf7, 0x7f, 0xff, 0x67, 0xeb, 0x2e, 0x59, 0x10, 0xfe, 0x09, 0xcf,
	0x69, 0x9e, 0xb0, 0x3a, 0xa5, 0x99, 0xc0, 0xd5, 0x2c, 0xa0, 0x82, 0xbc, 0xc2, 0x51, 0xc1, 0xca,
	0x9c, 0xe7, 0x34, 0x44, 0x79, 0xc1, 0x04, 0x33, 0x4c, 0x45, 0xa2, 0x81, 0x44, 0x3d, 0x79, 0xf5,
	0x3c, 0x62, 0x11, 0x53, 0x10, 0x6e, 0x4f, 0x1d, 0x7f, 0xd5, 0x77, 0x0e, 0x08, 0xa7, 0x98, 0x08,
	0x51, 0xc4, 0x41, 0x29, 0x28, 0xc7, 0xd5, 0x6c, 0x88, 0x7a, 0xd2, 0x3e, 0x32, 0x03, 0xae, 0x58,
	0x52, 0xa6, 0x3b, 0x62, 0x7a, 0x72, 0xca, 0x82, 0x72, 0x56, 0x16, 0x21, 0x2d, 0xb3, 0x58, 0x74,
	0xb0, 0xf3, 0x73, 0xa4, 0x8f, 0xdf, 0xb6, 0xc3, 0xbf, 0xcb, 0x69, 0x68, 0x4c, 0xf5, 0xb3, 0x8c,
	0xa4, 0xd4, 0x04, 0x36, 0x70, 0xc7, 0xde, 0xe5, 0x56, 0x42, 0x15, 0x37, 0x12, 0x4e, 0x6a, 0x92,
	0x26, 0x77, 0x4e, 0x1b, 0x39, 0xbe, 0x4a, 0x1a, 0x5f, 0x81, 0xfe, 0xa4, 0xa0, 0x9f, 0xcb, 0xb8,
	0xa0, 0xad, 0x0a, 0x37, 0x1f, 0xd9, 0xc0, 0x9d, 0xdc, 0x60, 0xd4, 0x79, 0x6f, 0xbd, 0xa0, 0xc1,
	0x0b, 0xaa, 0x66, 0xe8, 0x3e, 0x21, 0xa1, 0x62, 0xfd, 0xbd, 0x32, 0x6f, 0xba, 0x94, 0x50, 0xdb,
	0x4a, 0x78, 0xd0, 0xac, 0x91, 0xf0, 0x59, 0x27, 0xb9, 0x9f, 0x75, 0xfc, 0x03, 0xc8, 0xf8, 0xa2,
	0x8f, 0x77, 0x9e, 0xb8, 0x39, 0xb2, 0x47, 0xee, 0xe4, 0xe6, 0x1a, 0x9d, 0x5a, 0x3d, 0xf2, 0x7b,
	0xf4, 0x7d, 0x16, 0x0b, 0xef, 0x75, 0xaf, 0x3a, 0x34, 0x68, 0x24, 0xbc, 0xd8, 0x49, 0xf6, 0x29,
	0xe7, 0xc7, 0x6f, 0xf8, 0x74, 0xbf, 0x8c, 0xfb, 0x03, 0x6f, 0x64, 0xfa, 0x79, 0xb7, 0x78, 0xf3,
	0x4c, 0x39, 0x7f, 0x71, 0x4c, 0x1a, 0x7d, 0x50, 0xc8, 0x3d, 0x4b, 0xe2, 0xb0, 0xf6, 0x6e, 0x97,
	0x12, 0x82, 0xad, 0x84, 0x17, 0x5d, 0xe1, 0x4b, 0x96, 0xc6, 0x82, 0xa6, 0xb9, 0xa8, 0x1b, 0x09,
	0x2f, 0x3b, 0xf1, 0xff, 0x6f, 0x1c, 0xbf, 0x57, 0xb9, 0x7b, 0xfc, 0xed, 0x01, 0x6a, 0x7f, 0x1f,
	0x20, 0xf0, 0xde, 0x2c, 0xd7, 0x16, 0x58, 0xad, 0x2d, 0xf0, 0x67, 0x6d, 0x81, 0xef, 0x1b, 0x4b,
	0x5b, 0x6d, 0x2c, 0xed, 0xd7, 0xc6, 0xd2, 0x3e, 0x5e, 0xe7, 0x8b, 0x08, 0x91, 0x85, 0x40, 0x73,
	0x5a, 0xe1, 0x88, 0xe1, 0x8c, 0xcd, 0xe9, 0x91, 0xaf, 0x10, 0x9c, 0xab, 0xe7, 0xbf, 0xfd, 0x17,
	0x00, 0x00, 0xff, 0xff, 0x7e, 0x9e, 0x6d, 0x0c, 0xd3, 0x02, 0x00, 0x00,
}

func (this *GroupSpec) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GroupSpec)
	if !ok {
		that2, ok := that.(GroupSpec)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if !this.Requirements.Equal(&that1.Requirements) {
		return false
	}
	if len(this.Resources) != len(that1.Resources) {
		return false
	}
	for i := range this.Resources {
		if !this.Resources[i].Equal(&that1.Resources[i]) {
			return false
		}
	}
	if !this.Volume.Equal(that1.Volume) {
		return false
	}
	return true
}
func (m *GroupSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GroupSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GroupSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Volume != nil {
		{
			size, err := m.Volume.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGroupspec(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.Resources) > 0 {
		for iNdEx := len(m.Resources) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Resources[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGroupspec(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.Requirements.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGroupspec(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintGroupspec(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGroupspec(dAtA []byte, offset int, v uint64) int {
	offset -= sovGroupspec(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GroupSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovGroupspec(uint64(l))
	}
	l = m.Requirements.Size()
	n += 1 + l + sovGroupspec(uint64(l))
	if len(m.Resources) > 0 {
		for _, e := range m.Resources {
			l = e.Size()
			n += 1 + l + sovGroupspec(uint64(l))
		}
	}
	if m.Volume != nil {
		l = m.Volume.Size()
		n += 1 + l + sovGroupspec(uint64(l))
	}
	return n
}

func sovGroupspec(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGroupspec(x uint64) (n int) {
	return sovGroupspec(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GroupSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGroupspec
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GroupSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GroupSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGroupspec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGroupspec
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGroupspec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requirements", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGroupspec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGroupspec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGroupspec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Requirements.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGroupspec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGroupspec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGroupspec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Resources = append(m.Resources, ResourceUnit{})
			if err := m.Resources[len(m.Resources)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Volume", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGroupspec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGroupspec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGroupspec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Volume == nil {
				m.Volume = &v11.VolumePolicy{}
			}
			if err := m.Volume.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGroupspec(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGroupspec
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGroupspec(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGroupspec
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGroupspec
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGroupspec
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGroupspec
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGroupspec
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGroupspec
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGroupspec        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGroupspec          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGroupspec = fmt.Errorf("proto: unexpected end of group")
)
